- buffer.c
- device.c
- iio-private.h
- iio.h
- local.c
- network.c
- utilities.c
Implements buffer API enhancement discussed in issue #16
> Enhance buffer API

- bindings/python/iio.py
related to https://ez.analog.com/message/209741#209741
Signed-off-by: Ben Acland <benacland@gmail.com>
> sort the channels array on device or trigger init

- tests/iio_adi_xflow_check.c
use the same context in the monitor thread to make use context work
> tests/iio_adi_xflow_check: Add advanced context scan / creation

- tests/CMakeLists.txt
- tests/iio_attr.c
- tests/iio_info.c
improve the output of iio_info, and add iio_attr (a util which reads/write attributes).
> Test improvements

- .travis.yml
Signed-off-by: Michael Heimpold <mhei@heimpold.de>
> travis-ci: fix typo in matrix

- iiod/usbd.c
This avoids following warnings during USB device enumeration:
* No SuperSpeed endpoint companion for config Y  interface Y altsetting Z
ep N: using minimum values
> iiod: usbd: initialize the SuperSpeed Endpoint Companion descriptors

- channel.c
- device.c
read_each_attr()/iio_channel_attr_read_all() read all device or channel
attributes at once. The way this is implemented the server sends back a
packet with all the attribute values. For each value it also stores the
size of the value.
The current implementation blindly trusts this value that is store in the
received buffer and increments its pointer position accordingly. But the
data is untrusted data from the network and could contain random garbage.
If the length stored in the buffer is large enough to move the read pointer
beyond the buffer this will cause undefined behavior.
To prevent this make sure that the attribute length stored in the received
buffer is properly validated and read_each_attr()/iio_channel_attr_read_all()
do not access their receive data buffer beyond the amount of …
> Prevent out-of-bounds access in read_each_attr()/iio_channel_attr_read_all()

- mainpage.dox
Noticed this while reading the docs, very minor but might lead to confusion.
> Fix buffer/device mixup in docs

- network.c
The original implementation for Linux assumes the MSG_TRUNC flag is
supported. As of build 16299, Windows Subsystem for Linux presents a Linux
API but without support for MSG_TRUNC. The modification simply re-receives
the packet data without specifying MSG_PEEK, thus advancing the buffer
pointer.
Signed-off-by: JaredD <jareddpub@gmail.com>
> network: Add workaround for Microsoft Windows Subsystem for Linux

- mainpage.dox
add doc on triggered buffers needed triggers set up.
> add note about triggered buffers in dox source

- .travis.yml
- CI/travis/before_deploy
- CI/travis/get_ldist
- CI/travis/inside_centos_docker.sh
try to make the system find out, as this is more robust
> travis-ci: don't hard code distributions anymore

- .travis.yml
- CI/travis/inside_bionic_docker.sh
- CI/travis/inside_centos_docker.sh
- CI/travis/make_linux
The intent is to re-use some of these scripts for libad9361-iio, which has
quite a bit of the same build rules.
> build,travis: parametrize library name

- README.md
> README: Add links for issue tracking

- CI/travis/get_ldist
> CI/travis/get_ldist: &> /dev/null re-direction doesn't work in /bin/sh

- CI/travis/lib.sh
* check if script is present in build folder so it doesn't re-download stuff everything it gets included
* ensure wget is present on the machine (particularly docker)
> update lib.sh deployment logic

- examples/Makefile
- examples/adrv9009-iiostream.c
PR adds a streaming example for ADRV9009
> Add example for ADRV9009

- bindings/python/iio.py
Python: More robust loading of IIO library that works on different platforms.
This improvement is based on work of Emmanuel Blot (eblot).
Tested-by: Matej Kenda <matejken@gmail.com>
> Python: More robust loading of IIO library

- examples/.gitignore
> Update .gitignore in the examples dir

- examples/README.md
I will need to add signed-off-by before commit, but wanted to get people's opinion on what should be in this file.
> fix #59 - add a readme to the examples directory

- tests/iio_attr.c
Dan pointed out that #268 was mostly because iio_attr didn't allocate
enough room in it's internal buffers for some large kernel attributes.
To resolve this, move the 1k stack allocations to 16k heap allocations
via using malloc/free. This patch changes all potential buffers to
a malloc. This only effects the test utility iio_attr, not the core
library.
> ./tests/iio_attr : move from allocating space on stack to malloc

- iio.h
fixes some minor doxygen formatting & consistency issues in iio.h
Needed for automated man page generation, which I will add later this week.
> fixes some minor doxygen formatting & consistency issues in iio.h

- CI/travis/make_linux
- CMakeLists.txt
This shuffles around some of the top level cmake, so the doc isn't build if Doxygen is found - it needs to be turned on.
-Robin
> Promote with_doc

- CODE_OF_CONDUCT.md
As per https://opensource.guide/code-of-conduct/ create a code of conduct for the libiio project.
> Create Code of Conduct.md

- iiod-client.c
- network.c
This was taken from Lar's old branch "stresstest"
https://github.com/analogdevicesinc/libiio/commit/dc337057506507c35ab7185af810048eb2e69259
and adds a few more error output when things go wrong.
> Increase error reporting on iiod and network backend

- channel.c
- iio.h
Update the channel type and modifier lists against Linux 5.4.22.
> Update the channel type and modifier lists against Linux 5.4.22

- README_BUILD.md
Fix spelling and resolve #403 
Signed-off-by : Robin Getz <robin.getz@analog.com>
> README_BUILD.md : update with a few more Prerequisites

- context.c
- dns_sd.c
- dns_sd_avahi.c
- iiod/iiod.c
- usb.c
Fixes a few new coverity issues 
https://scan.coverity.com/projects/analogdevicesinc-libiio
More to come.
> coverity fixes

- buffer.c
- tests/iio_adi_xflow_check.c
- tests/iio_attr.c
- tests/iio_info.c
- tests/iio_readdev.c
- tests/iio_writedev.c
Fix minor nits that codacy points out.
Might add a few more.
> codacy fixes

- bindings/python/doc/iio_readdev.rst
- bindings/python/doc/iio_writedev.rst
- bindings/python/doc/index.rst
- bindings/python/doc/tools.rst
- bindings/python/examples/iio_readdev.py
- bindings/python/examples/iio_writedev.py
Implemented the iio_readdev and iio_writedev modules with Python bindings. These modules can be used as examples for sending and receiving buffers.
> python: added iio_readdev.py and iio_writedev.py

- bindings/python/iio.py
I have made some modification in order to improve the code quality of iio.py, as suggested by @rgetz [here](https://github.com/analogdevicesinc/libiio/issues/365#issuecomment-612333956).
> python: code quality improvements

- tests/iio_writedev.c
This code in iio_writedev.c:
368    sample_size = iio_device_get_sample_size(dev);
...
404        num_samples -= write_len / sample_size;
could potentially cause an error if sample_size is zero.
Catch that fault and error out. While we are here, check
for negative error codes, and also error out.
Reported by Coverity
> Coverity: Fix potential divide by zero.

- .travis.yml
- CMakeLists.txt
Reverts analogdevicesinc/libiio#453
This doesn't work. Will need to look at something else...
> Revert "Cmake/Coverity: Force coverity to check _everything_"

- examples/ad9361-iiostream.c
- examples/ad9371-iiostream.c
- examples/adrv9009-iiostream.c
- examples/dummy-iiostream.c
- examples/iio-monitor.c
Now that we added some things to the examples, fix the errors that were pointed out.
> fix examples

- dns_sd.c
- dns_sd_bonjour.c
- iiod-client.c
- iiod/ops.c
- iiod/usbd.c
- local.c
- network.c
- utilities.c
this resolves/removes all the sprintf and strcpy, except in the examples, and tests.
> fix remaining snprintf issues

- examples/iio-monitor.c
minor fixes to iio_monitor that coverity and codacy pointed out.
- replace sprintf
- fix double free
> fix iio monitor

- bindings/python/doc/channel.rst
- bindings/python/doc/device.rst
- bindings/python/iio.py
Added the Sphinx documentation for the DeviceBufferAttr and DeviceDebugAttr classes under the Device menu, as stated here #449.
> doc: added DeviceBufferAttr and DeviceDebugAttr in Sphinx.

- .prospector.yml
- .pylintrc
- bindings/python/iio.py
This will add some python code formatting detaults (black) and fix some issues pointed out by the pylint file.
> python binding improvements

- bindings/python/examples/iio_readdev.py
- bindings/python/examples/iio_writedev.py
Since @cristi-iacob is on vacation this week, take #499 and add a few things to fix all the issues.
> rework python examples

- bindings/python/doc/examples.rst
- bindings/python/doc/iio_attr.rst
- bindings/python/examples/iio_attr.py
Implemented the iio_attr module with Python bindings.
> python: added iio_attr with Python bindings.

- bindings/python/examples/iio_info.py
I have rewritten the iio_info.py module in a similar fashion as the iio_readdev, iio_writedev and iio_attr modules.
> python: iio_info.py rewrite.

- context.c
- tests/iio_adi_xflow_check.c
- tests/iio_attr.c
- tests/iio_common.c
- tests/iio_readdev.c
- tests/iio_writedev.c
two issues while tracking down others...
> fix recent coverity issues

- usb.c
> fix usb when compiled with MSVC

- mainpage.dox
- man/iio_attr.1.in
> update some doc

- iiod/iiod.c
In certain embedded cases, iiod may start before networking or dbus is
fully alive on a system (like on Pluto and M2k).
This change ensures that when we are trying to connect to avahi, and
register on the network, we give things a few moments to stablize (re-trying)
before we fail.
tested on PlutoSDR, and Zedboard + FMCOMMS3
> iiod: Make startup (with Avahi) more robust.

- README_BUILD.md
Signed-off-by: Virgil Litan <virgil.litan@analog.com>
> doc: fix typo in build guide

- appveyor.yml
- network.c
The appveyor job has been failing for the last couple of weeks.
Fix it.
> ci,build: fix build with appveyor; bump some package versions & fix variable type

- CI/travis/before_install_linux
- CI/travis/make_linux
- cmake/LinuxPackaging.cmake
Small collection of tweaks in the build and the CI.
> ci,build: misc build tweaks

- serial.c
> serial: Detect timeout when writing to serial port

- channel.c
- iio-backend.h
- iio-private.h
- local.c
- usb.c
Fixes these issues:
../local.c: In function ‘add_scan_elements’:
../local.c:1701:38: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 0 and 1023 [-Wformat-truncation=]
1701 |   iio_snprintf(buf, sizeof(buf), "%s/%s", path, entry->d_name);
|                                      ^~
In file included from ../local.c:10:
../iio-private.h:38:22: note: ‘snprintf’ output between 2 and 1280 bytes into a destination of size 1024
38 | #define iio_snprintf snprintf
../local.c:1701:3: note: in expansion of macro ‘iio_snprintf’
1701 |   iio_snprintf(buf, sizeof(buf), "%s/%s", path, entry->d_name);
|   ^~~~~~~~~~~~
../local.c: In function ‘add_buffer_attributes’:
../local.c:1701:38: warning: ‘%s’ directive output may be truncated writing up to 255 …
> Small cleanups

- CMakeLists.txt
- tests/iio_stresstest.c
A set of fixes to build libiio under MinGW / msys2.
> Fix MinGW build

- xml.c
A set of cleanups to the XML backend, to make sure that the error codes are carried all the way from the deeply nested functions back to the caller function.
> Xml backend cleanups

- xml.c
When libiio is unloaded (when the client program exits), cleanup libxml2
so that memory analyzer tools like Valgrind won't detect a memory leak.
> xml: Cleanup libxml2 parser when exiting library

- azure-pipelines.yml
> Corrected code

- channel.c
- context.c
- device.c
- iio-private.h
Create function for repeated code and sanitize where needed.
> Improve xml sanitization

- examples/ad9361-iiostream.c
- examples/ad9371-iiostream.c
- examples/adrv9009-iiostream.c
Fix -Wshadow warnings in the examples applications....
> Fix examples warnings

- bindings/python/examples/iio_readdev.py
> python: Fixes --samples argument by multiplying num_samples by sample_size

- CMakeLists.txt
- iio-backend.h
- iio-lock.h
- iio-private.h
- lock-windows.c
- lock.c
This set of commits add support for condition variables, and creating/joining threads, on Unix and Windows. This will be used to handle the async iiod-client protocol, which requires threads for communication.
> lock: Add support for condition variables and threads

- iiod/ops.c
The client might call iio_device_set_kernel_buffers_count() right after
destroying the device's buffer with iio_buffer_destroy(). Since the
first operation cannot work if the buffer is enabled, we must wait until
the buffer has been effectively disabled before the setting can be
applied.
> iiod: Avoid race between buffer destroy and set buffers count

- bindings/python/iio.py
Buffer creation was broken since PR #636.
> python: Fix circular dependencies between objects

- iiod/ops.c
Commit aad53e3 ("iiod: Update read_line() to work with UART") made IIOD
able to read its input from UART, but broke USB support at the same
time.
This commit changes the read_line() function so that it works as
expected with both UART and USB transports.
The bug was reported on EZ:
https://ez.analog.com/linux-software-drivers/f/q-a/550894/modifying-libiio-recipe/436242
> iiod: fix read_line() for USB

- azure-pipelines.yml
Add windows artifacts to zip file in order to match the description of the artifacts on GitHub libiio [README.md](https://github.com/analogdevicesinc/libiio#readme) file.
> Archive windows artifacts

- CI/travis/prepare_assets.sh
> CI: fix PushArtifacts stage

- CI/travis/inside_docker.sh
- CI/travis/lib.sh
- azure-pipelines.yml
Fix Fedora-34 builds on Azure. In the 'Documentation' step, 'build' folder is removed so I swap the 'Documentation' and 'CopyFiles' steps.
Second commit: Linux repo have some links to libiio CI/travis folder. Temporary CI/travis folder will be added to fix Azure builds until finding a final solution.
> CI: fix builds

- CI/azure/ci-ubuntu.sh
- azure-pipelines.yml
This makes testing PRs easier/more convient for those who want to check
out various platforms.
> CI: Save artifacts on Azure pipelines for builds, including PRs

- dns_sd_windows.c
Both the Linux and Mac implemations of DNS SD ensures something is there
before passing the host information up the stack. The Windows
implemnation was missing this, so add it.
Fix #559
> Windows DNS SD : add port knocking like other implementations

- examples/ad9361-iiostream.c
- examples/ad9371-iiostream.c
- examples/adrv9002-iiostream.c
- examples/adrv9009-iiostream.c
Fix build of the examples, which were not updated to use the latest API.
> examples: Fix build

- CMakeLists.txt
- libiio.iss.cmakein
Update the script so that the new libiio1.lib and libiio1.dll will be
installed.
> Inno Setup: Update script to point to new libiio

- network.c
It takes some time for private networks (cross over cables, with
unconfigured networks on them) to propagate through Window's normal
routing tables (from what I can tell), so this just increases the
ability to work around that and get the answers when we need.
> mdns: early private networks on Windows are flakey

- iiod-client.c
It is not guaranteed that the command will be sent in a single call to
.write(). Therefore we need to send the command with
iiod_client_write_all().
> iiod-client: Use iiod_client_write_all() in iiod_client_exec_command()

- CI/azure/prepare_assets.sh
- artifact_manifest.txt.cmakein
- azure-pipelines.yml
Add Ubuntu-22.04 and macOS-12 to Azure Pipelines builds
> CI:add new YAML VM Images

- azure-pipelines.yml
> Disable libzstd for macos builds

- cmake/Install.cmake
- dns_sd_windows.c
- include/iio/iio.h
- tests/CMakeLists.txt
A few commits to fix different build problems happening with the dev branch on Ubuntu 18.04, OSX and Windows.
> Build fixes for the dev branch

- iiod/init/iiod.service.cmakein
Signed-off-by: A. Maitland Bottoms <bottoms@debian.org>
> service documentation

- Doxyfile.in
- bindings/csharp/Doxyfile.in
Keep build path and build time out of the generated documentation.
Signed-off-by: A. Maitland Bottoms <bottoms@debian.org>
> doxygen reproducible build

- azure-pipelines.yml
Remove deprecated os versions from Azure builds.
> CI:update ci

- usb.c
Create one iiod-client per USB endpoints couple, for use with buffer
operations. Properly initialize the iiod_client_pdata structures, and
implement the .readbuf() and .writebuf() callbacks for use with the
regular IIOD protocol.
> usb: Update to work with new interface

- bindings/python/doc/conf.py.in
> CI:fix sphinx error

- azure-pipelines.yml
Commit 1: add task for Python to use latest 3.x version
Commit 2: fix sphinx-build error
> CI: update and fix

- serial.c
Calling sp_flush() does not seem to be enough to flush the input buffer with some serial-to-USB adapters.
> serial: Properly flush the input buffer

- channel.c
Support attribute names that start with the channel's label to avoid breaking compatibility with old kernels, which did not offer a 'label' attribute, and caused Libiio to sometimes misdetect the channel's extended name as being part of the attribute name.
> channel: Support attribute names that start with the channel's label

- azure-pipelines.yml
Add pkg-config.
Signed-off-by: Raluca Groza <raluca.groza@analog.com>
> CI: Fix macOS_11

- usb.c
libiio scans via libusb when the usb backend is built in. For many embedded linux targets that support On The Go (OTG) the USB port can be configured as device or host. Sometimes, end users may want to scan for local devices when the OTG is configured as a device (and there aren't any USB hosts).
The issue with this is libusb returns an error when there are not any hosts. So - on linux - catch that, and override the error handling.
New functionality is when Linux's OTG USB is in device mode, usb scans can still take place.
This fixes issue #925 (iio_attr -a fails on plutoSDR).
> usb: don't error during a scan on linux when there are no usb hosts.

- tests/gen_code.c
The strchr() return a NULL if the character is not found. Make sure to handle that.
> tests: don't dereference a var before checking it.

- CI/azure/check_README_BUILD.sh
- README_BUILD.md
- azure-pipelines.yml
and make sure it can't go out of date
> Rgetz update README_BUILD.md file

- Contributors.md
from the script in the bottom of that file.
It's been a bit since this has been updated, so the numbers/names have changed a bit.
> update Contributors file

- CMakeLists.txt
- bindings/cpp/examples/iiopp-enum.cpp
- bindings/cpp/iiopp.h
- doc/index.html.in
This adds some minor improvements that came up after the previous pull request was accepted.
> Polishing for C++

- azure-pipelines.yml
Clean workspace before each build on macOS builds.
> CI: fix macOS checkout

- dns_sd.h
- dns_sd_avahi.c
- dns_sd_windows.c
- iio-private.h
- iio.h
- network.c
- utilities.c
My take at #1003. Just creating a draft PR to get the CI builds for now.
> Libiio DNS/SD scan fixes

- dns_sd_windows.c
The getnameinfo() function already returned the interface number appended to the IPv6 address in ip_address_to_string(); the problem was that the interface number was not properly specified in the sockaddr argument.
Now, the sin6_scope_id field (which contains the interface number on Windows) is correctly set, to the interface number of the "from" sockaddr argument.
From what I understand, one problem was that the IPv6 address was discovered twice; once with the mDNS socket on IPv6, and once with the mDNS socket on IPv4. The AAAA entry discovered from the IPv4 socket would override the one obtained from the IPv6 socket, but wouldn't contain information about the interface number.
Address this issue by only handling AAAA entries on the IPv6 interface.
> dns_sd_windows: Fix discovery on IPv6 once again

- CI/azure/prepare_assets.sh
Fix Windows zip file in release.
> CI: fix empty Windows.zip release artifact

- azure-pipelines.yml
Add branch `next_stable` to CI triggers
> CI: add next_stable branch to CI triggers

- iiod/dns-sd.c
- iiod/iiod.c
print out IP numbers when clients connect.
> Rgetz iiod enable ip numbers

- CI/publish_deps.ps1
Fix the paths in publish_deps.ps1 as they changed in the build machine.
> CI: Fix MinGW build

- CI/publish_deps.ps1
Merge the CI fix that's in `libiio-v0` because we want it in `main` as well.
> Merge libiio-v0 branch back into main

- azure-pipelines.yml
- bindings/cpp/iiopp.h
- iiod/dns-sd.c
Cherry-pick three commits from the main branch.
> Update libiio v0 20231113

- .github/workflows/freebsd.yml
Update freebsd vm to latest version
> Update freebsd vm to latest version

- utils/iio_info.c
- utils/iio_rwdev.c
Drop leftover -s option in iio_info, and support specifying the trigger rate in iio_rwdev.
> Small update to utilities

- compat.c
- dns_sd.c
> Misc. fixes

- CI/publish_deps.ps1
- azure-pipelines.yml
- bindings/cpp/iiopp.h
- iiod/dns-sd.c
- xml.c
Cherry-pick commits for different fixes from libiio-v0 to 2022_r2 branch in order to build 2022_r2 Patch 1.
> Cherry pick from libiio v0

- bindings/cpp/iiopp.h
> Solve #1139 by returning optionals where C-API returns NULL for objects

- azure-pipelines.yml
Add build for Debian12 arm architecture which is the distribution of Kuiper2.0
> Add build for bookworm arm architecture

- CI/publish_deps.ps1
Cherry-pick commit from main that fixes mingw build
> Fix ghc version for libiio-v0 branch

- azure-pipelines.yml
Microsoft will remove macOS-11 support.
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#recent-updates
> Remove build of macOS-11

- CI/azure/check_kernel.sh
This would have found and avoided #1176
> CI: ensure we also check the modifier strings against mainline kernel

- .github/workflows/freebsd.yml
> Update FreeBSD GH Action to run on PRs

- .github/workflows/freebsd.yml
Update the version of the FreeBSD to avoid CI throwing error due to mismatches between the kernel and the package repository:
```
Run vmactions/freebsd-vm@v1
release: [13](https://github.com/analogdevicesinc/libiio/actions/runs/14967326081/job/42040122788#step:3:14).2
arch: 
nat: 
mem: 
cpu: 
Importing VM
Run onBeforeStartVM
Run startVM
Run onStarted in VM
Initialize files in VM
envs:
Run onInitialized in VM
Run 'prepare' in VM
Running prepare: pkg update
pkg install -y git cmake ninja libxml2 bison flex libserialport avahi doxygen graphviz
exec ssh: pkg update
pkg install -y git cmake ninja libxml2 bison flex libserialport avahi doxygen graphviz
/usr/bin/bash /home/runner/work/_actions/vmactions/freebsd-vm/v1/run.sh execSSHSH
Config file: freebsd-13.2.conf
Updating FreeBSD repository …
```
> CI: Update FreeBSD to 13.4

- CI/azure/build_mingw.sh
> mingw64 - fix CI issues

- deps/libini/.gitrepo
- deps/libini/ini.h
- deps/libini/libini.c
Update the libini subrepo to latest commit.
> Update libini subrepo

- CI/azure/generateDocumentationAndDeploy.sh.in
> generateDocumentationandDeploy: update branch to main

- stream.c
Add braces after the for() loop to make it clear the next if() statement is part of it. This helps with readability.
> stream: improve readability in iio_stream_destroy()

- utils/iio_info.c
Do not print the values of debug attributes in iio_info.
It has come up multiple times that reading debug attributes can cause unintended side effects. For example if the IIO driver is currently doing a buffered read, reading the debug attribute could cause the chip to exit data capture mode and break the buffered read. Also, some registers could clear or reset something, like an interrupt, when a status register is read.
So general-purpose tools like iio_info should not read debug attributes that the user did not explicitly request.
Closes: https://github.com/analogdevicesinc/libiio/issues/1304
Link: https://lore.kernel.org/linux-iio/20250621170824.249c6b0c@jic23-huawei/
> utils: iio_info: do not print debug attribute values

- man/iio_attr.1.in
- man/iio_common_opts.1
- man/iio_info.1.in
- man/iio_rwdev.1.in
- man/iio_stresstest.1.in
- man/iiod.1.in
- utils/iio_genxml.c
- utils/iio_info.c
- utils/iio_stresstest.c
The help menu of several `utils` are outdated. This PR makes the necessary updates.
> Update utils help menu

- CI/build_win_msvc.ps1
- README_BUILD.md
- artifact_manifest.txt.cmakein
- azure-pipelines.yml
- examples/CMakeLists.txt
- examples/README.md
- examples/ad9361-iiostream.c
- examples/ad9371-iiostream.c
- examples/adrv9002-iiostream.c
- examples/adrv9009-iiostream.c
- examples/dummy-iiostream.c
- iiod/CMakeLists.txt
Several small fixes came up along the way and added up to a noticeable change.
> Several small fixes
