analogdevicesinc/libiio

CMakeLists.txt
Do not force the type of library because some architectures (such as
BlackFin from AnalogDevice) do not support shared object.
Signed-off-by: Samuel Martin <s.martin49@gmail.com>
=> cmake: let BUILD_SHARED_LIBS drive the type of library built

bindings/python/iio.py
Thanks for creating libiio and the Python bindings!
I found this small bug while trying to collect data from an AD9361 in Python.  After fixing this, everything worked as expected.
=> Python: Fix bug in buffer read()/write() -- add missing "self".

buffer.c
Previous implementation of iio_buffer_first() considered that a
struct iio_buffer always contains samples for all the channels of the
device, for disabled channels. This is actually wrong, and disabled
channels should be ignored during offset calculation of a given enabled
channel.
It implements the same strategy as iio_buffer_foreach_sample().
Change-Id: I6df5a3ec766d0490d94d72cf67db2e6c1d3b76c2
=> Avoid to increment ptr in iio_buffer_first() for disabled channels

tests/iio_readdev.c
be in agreement with Documentation/ABI/testing/sysfs-bus-iio#L37 and use
'sampling_frequency' rather than 'frequency'
Signed-off-by: Marc Titinger <mtitinger@baylibre.com>
=> iio_readdev: fix ABI usage for sampling frequency with trigger devices

buffer.c, channel.c, device.c, examples/Makefile, examples/dummy-iiostream.c, iio.h, local.c, mainpage.dox, tests/iio_info.c, xml.c
`iio_chan_type` `IIO_ROT` uses the repeat channel `iio_chan_spec.scan_type.repeat` to store repeated elements in a channel without modifiers.
This patch series adds support to `libiio` and creates a new example tool that exercises the `iio_dummy` driver. For testing this series the `iio_dummy` can be patched to include the `IIO_ROT` channel. See https://github.com/lucasrangit/linux-iio/pull/1 .
Signed-off-by: Lucas Magasweran <lucas.magasweran@daqri.com>
---
Changes since v1:
* tests: iio_info: compared `format->repeat > 1` for consistent output and avoid duplicated `printf`
* examples: dummy: remove debug print of scan channel size and repeat count
and squashed commits since this is a new sample tool
* added missing Signed-off-by to commits
Changes since v2:
* iio: moved `struct …
=> [RFC PATCH v5] iio: repeat channel support and dummy client example

bindings/CMakeLists.txt, bindings/matlab/CMakeLists.txt, bindings/matlab/iio-wrapper.h, bindings/matlab/iio_installer_script.m, bindings/matlab/iio_sys_obj.m, bindings/matlab/iio_sys_obj_matlab.m, bindings/matlab/libiio_if.m, bindings/matlab/libiio_if_daq2.m, iio.h
MATLAB requires a few workarounds for its header parsing, library
loading, and mex usage to work properly.
MATLAB_MEX_FILE is defined via the MATLAB mex build process while
MATLAB_LOADLIBRARY is defined via a header wrapper used by the libiio
MATLAB bindings.
=> iio.h: add checks for MATLAB workarounds

appveyor.yml
Precursor to adding support to the installer to properly install the matlab bindings on windows.
=> appveyor: include matlab bindings in the zip file artifacts

.travis.yml, CMakeLists.txt, README.md
Update the CMake, so we build nightly debs & rpms, and set up things for coverity with travis.
-Robin
=> Merge travis branch #2

buffer.c
Samples are aligned to their own size, but the alignment is
from the buffer start, not an absolute (virtual) memory alignment.
For example, timestamps are added like this in the kernel:
size_t ts_offset = indio_dev->scan_bytes / sizeof(int64_t) - 1;
((int64_t *)data)[ts_offset] = timestamp;
Also:
```
static int iio_compute_scan_bytes(struct iio_dev *indio_dev,
const unsigned long *mask, bool timestamp)
{
const struct iio_chan_spec *ch;
unsigned bytes = 0;
int length, i;
/* How much space will the demuxed element take? */
for_each_set_bit(i, mask, indio_dev->masklength) {
...
bytes = ALIGN(bytes, length);
^^^^^^^^^^^^^^^^^^^^
bytes += length;
}
```
=> iio_buffer: fix samples alignment computation

iio.h, local.c
Since commit 4ebd0743, returned negative errno code is always `-EIO`
on `read()` error instead of using `-errno`.
For example, `-EAGAIN` was not returned anymore in blocking mode when
no data was available.
Also fix documentation regarding `-EAGAIN` from `iio_buffer_refill()` and
`iio_buffer_push()`.
=> Local backend: return negative errno code on local_read/write() error

CMakeLists.txt, bindings/matlab/CMakeLists.txt, bindings/matlab/iio-wrapper.h, iio-config.h.cmakein, iio-private.h, scan.c
Add scan_block helper functions for use in languages (e.g. MATLAB) that
cannot easily iterate over a list of pointers.
The scan_block functions enable the creation / scanning of a scan context
and the retrival of context_info via an index value.
Signed-off-by: Matt Fornero <matt.fornero@mathworks.com>
=> matlab: Add scan_block helper API

local.c
After freeing protected_attrs array, set it to NULL. Otherwise, it
could be freed a second time. It can happen in create_device() when
handle_scan_elements() returns a failure, forcing create_device() to
abort.
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
=> Local backend: Avoid double free when create_device is aborted.

tests/iio_attr.c
man 3 printf recommends to use z length modifier for ssize_t.
This fixes several warnings (wrapped line for readability):
warning: format '%li' expects argument of type 'long int',
but argument 3 has type 'ssize_t {aka int}' [-Wformat=]
Signed-off-by: Michael Heimpold <mhei@heimpold.de>
=> test/iio_attr: fix compiler warnings about printf arguments

examples/ad9361-iiostream.c
Make sure we always evaluate the expression even when NDEBUG is defined.
=> examples/ad9361-iiostream: Fix assert() usage with NDEBUG

tests/iio_attr.c
providing the [-q | --quiet] option together with a complete
device/channel/debug attribute path will only write the value to stdout.
Likewise for device/channel/debug attribute writes, where only the
readback value is written to stdout.
=> iio_attr: Add quiet mode as discussed in #106

CI/travis/before_deploy
These additions were requested by MathWorks to make their installation easier.  It will remove the requirement for a compiler for their HSP.
Signed-off-by: Travis Collins <travis.collins@analog.com>
=> Updated OSX tar deploy to be friendly with MathWorks HSP.

iiod/ops.c
Fix a segfault when setting the kernel buffers by checking for a valid
device before calling iio_device_set_kernel_buffers_count.
Signed-off-by: Andreas Brauchli <andreas.brauchli@sensirion.com>
=> iiod: fix crash setting buffers on invalid device

channel.c, iio.h
Update the channel type and modifier lists against Linux 4.14-rc8.
Signed-off-by: Andreas Brauchli <andreas.brauchli@sensirion.com>
=> Update channel type and modifier lists

CMakeLists.txt
This makes it easier (possible) for those who are using distributions that
don't keep up to libserialport uptodate (like Ubuntu 16 LTS).
You can build without this, just not automatically (it requires some command line options).
=> Cmake: If the version of libserialport isn't 0.1.1; don't fail, just warn

.travis.yml, CI/travis/before_deploy
make releases/tags on travis-ci more robust, and handle more issues.
- release OS-X files
- don't overwrite files on release.
=> Travis ci3

examples/Makefile, examples/ad9371-iiostream.c
Be aware given the fact that AD9371/5 minimum basband rate is >= 30.72MSPS
it's almost impossible to keep up in software. In order to use this some
decimation / processing needs to be done in the FPGA fabric/PL.
=> examples/ad9371-iiostream.c: Add AD9371/5 IIO Streaming example

channel.c, iio-private.h, local.c
libiio currently has issues identifying the channel identifier (channel_id)
when a driver reports multiple attributes of the same type (e.g.
IIO_CONCENTRATION) with a name extension (.extend_name field in
struct iio_chan_spec) as it tries to resolve the name extension as the
modifier (e.g. IIO_MOD_VOC). In this case the startup routine
(local_create_context) fails to establish a valid context and aborts.
This patch defuses the situation by resolving the second-to-last underscore
(_) separated segment as the modifier, leaving room for a name extension
that itself potentially contains underscores.
* Modify find_channel_modifier to find the modifier in the second-to-last
underscore separated segment.
Also, report the offset from the beginning of the string until the
position of the modifier, …
=> RFC: Fix channel identifier heuristics

local.c
Hi,
I'm using a setup where I stream data to and from an FPGA via the libiio buffer (using dmaengine)
While using the non-blocking buffer `iio_buffer_set_blocking_mode()` with `iio_buffer_refill()`
I stumbled upon some weird error:
After an initially successful received buffer and a subsequent timeout, it would always give
> "Unable to enqueue block"
I looked into the code and think I spotted the error, at least the patch fixes the behaviour for me.
I think this is an error, which brakes the behaviour for all non-blocking cases as soon as a timeout occurs.
The underlying problem is, that upon returning from a buffer operation with EAGAIN the `pdata->last_dequeued` block id is not invalidated, and also there is no block being dequeued in the current run. On the next refill(s) libiio tries …
=> Fix: local buffer tries to re-enqueue block after an error, breaking all future get buffer ops

bindings/python/iio.py
Added a new parameter (ctx = None) for the iio.Buffer class constructor. This parameter is stored in self._ctx as a reference to a Context variable. This reference ensures that the Context outlives the buffer, if this is not the case a segmentation violation will occur when destroying the buffer.
=> Allow iio.Buffer to be aware of the Context, to avoid a segmentation violation

tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c
A lot of the IIO tools currently assumes that the argument for an option that
is parsed by getopt_long() is in the argv[] following the option and then
the combination of option and argument always consumes two argv[] entries.
This is not necessarily true though. getopt_long() accepts option and
argument in the same argv[] entry. For short options the argument can
directly follow the option character and for long options the argument can
follow in the same argv[] entry separated by a '=' character.
E.g. both -u ip:192.168.1.1 and -uip:192.168.1.1 as well as --uri
192.168.1.1 and --uri=192.168.1.1 are equivalent and all valid.
As a result of this the tools will show undefined behavior when
option and argument are passed in the same argv[] entry (E.g. crash with a
segmentation fault).
To …
=> Fix optarg() handling

CMakeLists.txt, iiod/CMakeLists.txt, iiod/init/iiod.conf.cmakein, iiod/init/iiod.init.cmakein, iiod/init/iiod.service.cmakein
My goal is to update the openembedded/Yocto recipe for libiio. I'm using current Yocto with usrmerge flag enabled. This requires these two patches to build.
Installing udev rules to /usr/lib/udev/rules.d instead of /lib/udev/rules.d is common for systemd based Linux distributions.
=> Improve install

tests/iio_adi_xflow_check.c
The monitor thread must be joined before the call
to iio_context_destroy, otherwise iio_device_reg_read
and iio_device_reg_write might be called after context
destruction.
Signed-off-by: Julien Malik <julien.malik@paraiso.me>
=> iio_adi_xflow_check: Avoid accessing device after context destruction

tests/CMakeLists.txt, tests/iio_writedev.c
This test program uses the libiio library to read standard input and write
as raw stream to a device. This utility is vastly based on iio_readdev.
It adds one more parameter option to use cyclic buffers.
=> tests/iio_writedev: Add iio_writedev analogous to iio_readdev

local.c
Commit e6754cb84a8b ("local: Return error when no blocks could be
allocated") made the wrong assumption that the BLOCK_ALLOC_IOCTL will
return the ENOSYS error when high-speed mode is not supported. This is not
the case though and the ioctl returns the EINVAL error instead.
This breaks low-speed support since libiio now assumes that high-speed mode
is always supported and something went wrong when trying to allocate the
high-speed buffer and never tries to fallback to low-speed mode.
Unfortunately it is not possible to distinguish between a EINVAL that means
high-speed mode is not supported and a EINVAL that means high-speed mode is
supported but something went wrong when allocating the high-speed buffer.
To avoid this use the BLOCK_FREE_IOCTL to check whether high-speed mode is
supported …
=> local: Fix low-speed mode

examples/dummy-iiostream.c
The current instructions for setting up the environment for dummy IIO
device testing contain a few small mistakes.
Fix those mistakes and expand a bit on the steps that need to be done.
Thanks to Markus Roppelt for providing these new instructions.
=> examples/dummy-iiostream: Fix instructions

appveyor.yml
The old '2015.1.{build}' format is a bit confusing, because it gives the
impression that something is stuck in the past.
Change this to '{branch}.{build}'.
That way we don't need to care about date/time, since Appveyor will track
that anyway.
=> appveyor.yml: change versioning to '{branch}.{build}' format

iio.h
Fixed misspelling of "function" spelled as "fonction" in the
documentation of iio_buffer_start().
=> spelling fonction->function

.gitignore, CI/travis/before_deploy, CI/travis/before_install_darwin, CI/travis/before_install_linux, CI/travis/deploy, CI/travis/make_darwin, CI/travis/make_linux
As scripts grow in size, it's a good idea to exit & fail them on the first non-zero exit code.
That also enforces us to re-think the code, and not ignore any non-successful parts of the CI scripts.
=> CI/travis: make shell scripts more pendantic

.travis.yml, CI/travis/before_install_linux, CI/travis/inside_centos_docker.sh, CI/travis/make_linux, cmake/LinuxPackaging.cmake
Adapted from blog-post:
https://derekweitzel.com/2016/05/03/building-centos-packages-on-travisci/
This essentially uses CentOS docker images to run the libiio build and
create RPM packages, which is a bit closer to the real-world case of RPM
usage.
We're not doing any deployments of these files just yet.
This just builds them and confirms that we can build and install on
CentOS, and offers the procedure to do it.
A later change-set will add deployment of CentOS RPMs, since these seem to
be interesting for people.
=> build,CI/travis: setup CentOS testing

appveyor.yml
It seems that the latest version provided by appveyor (7.61.1-3) breaks some dependencies. Use the last
version which was known to work (7.61.1-2) until things get fixed.
=> appveyor.yml: Downgrade curl in order to fix the appveyor builds.

CMakeLists.txt, context.c, iio-private.h, local.c, sort.c, sort.h
when creating internal structures, sort them. In this way, other iio utilities
will output information in an easy to read/compare way.
This has no functionality difference, except to add a small
negative performance, but it makes the output of iio_attr and
iio_info, much easier to track by hand.
=> local: Sort devices, channels and attributes

context.c, local.c, sort.c, sort.h
- change functions names to more descriptive iio_*_compare
- move attribute sorting into context.c
- when sorting iio_channel, if index is the same, use ID
- fix whitespace issues that were accidently committed
=> minor sorting cleanups

bindings/matlab/iio_sys_obj_matlab.m
This change to the MATLAB bindings actually enables the FIR after loading it. This is how the current examples expect the functionality of the writeFirData function to work.
Signed-off-by: Travis Collins <travis.collins@analog.com>
=> ML bindings FIR load fix

.travis.yml
Currenty - when travis-ci builds for centos, the LDIST is set to trusty, so things get deployed with the trusty namespace. Fix that.
Signed-off-by: Robin Getz <Robin.Getz@analog.com>
=> travis : Add the LDIST for centos

usb.c
This added the entire usb interface (bus and address) in the error message, which was not there.
=> usb: be more verbose when unable to claim an interface

CMakeLists.txt, iio-config.h.cmakein, usb.c
When debugging, it's always nice to know the libusb version. This makes it easy to find.
=> usb: add libusb version to context attributes

usb.c
Experimental testing shows that with the current timeout if the remote system
is under high load the timeout is triggered occasionally.
To mitigate this issue increase the timeout.
=> usb: Increase ctrl pipe timeout

buffer.c
Previously, the index field of struct iio_channel was being used to test
against the buffer field of struct iio_device and struct iio_buffer.
This is incorrect because the index of the first channel may be non-zero
and the indexes may not be contiguous. For further evidence, look at
iio_channel_enable/disable() which use number rather than index.
=> Fix bug in mask bit tests

buffer.c, iiod/ops.c
From: #198 
Previously, the index field of struct iio_channel was being used to test
against the buffer field of struct iio_device and struct iio_buffer.
This is incorrect because the index of the first channel may be non-zero
and the indexes may not be contiguous. For further evidence, look at
iio_channel_enable/disable() which use number rather than index.
=> IIOD: Fix bug in mask bit tests (continued)

local.c
When a enabling a buffer fails (in the case of triggered buffer not having a trigger set up), the error is currently ignored.
Ensure that errors are passed back up the stack for end user debugging.
Signed-off-by: Robin Getz <Robin.Getz@analog.com>
=> local: pass errors up the stack

local.c
If global attributes are added after sorting, they are not included
in the sort, which defeats the purpose of things. This puts things
in the proper order (add all the attributes, then sort them).
=> sorting: ensure sorting happens after global attributes are added

.travis.yml, CI/travis/before_install_linux, CI/travis/inside_bionic_docker.sh, CI/travis/make_linux, cmake/LinuxPackaging.cmake
- Add a docker build for Ubuntu 18.04.1 LTS (Bionic Beaver) : EOL April 2023.
- Ubuntu 12.04.5 LTS reached its regular End of Life on April 28, 2017 so we should remove the corresponding Travis CI build. 
- Builds with Xcode 6.4 in Travis CI are deprecated and will be removed in January 2019, so we can remove the Xcode 6.4 builds from Travis CI.
Signed-off-by: Alexandra.Trifan <Alexandra.Trifan@analog.com>
=> travis-ci: add build for Ubuntu 18.04 and drop Ubuntu 12.04

channel.c, tests/iio_attr.c, tests/iio_info.c
In recent versions of gcc, there are a few places where gcc warns:
iio_info.c: In function ‘main’:
iio_info.c:333:41: warning: ‘%u’ directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Wformat-truncation=]
snprintf(repeat, sizeof(repeat), "X%u",
^~
This fixes the warn by increasing the size of the buffer to 12 from 8.
No functional differences.
=> fix snprintf warnings from gcc 8

CI/travis/before_deploy
properly export the var LDIST, so it can be used in other deployment scripts,
like ./CI/travis/deploy
=> deployment : export the LDIST var which is needed in other scripts

appveyor.yml
For some reason, cmake in appveyor is failing since it can't find dot; so install it.
=> appveyor: install graphviz

README.md
I turned on https://codedocs.xyz/ for libiio - so start pointing people to it
=> README.md : Update with links to doc

channel.c
Untested attempt to fix issue #219:
iio_channel_get_modifier and
iio_channel_get_type seems to work incorrectly.
=> channel: Fix #219 get_modifier and get_type seems to work incorrectly

.travis.yml, CI/travis/before_deploy, CI/travis/deploy, CI/travis/lib.sh
These patches sexpose a security risk, by potentially displaying secret
information in the logs.
=> Revert ".travis.yml: move SSH key logic into shell script from yaml file

.travis.yml, CI/travis/after_deploy, CI/travis/jobs_running_cnt.py, CI/travis/lib.sh
Let's start a "pipeline", where the libiio build triggers a
`libad9361-iio`, which will trigger other builds as well.
We're getting to a point where the lack of automation is starting to hinder
us a bit and changing things in `libiio` are not visible along the way,
until it gets a bit late.
There's a Python script that each job would run, to check if it's the last
job (in the parallel CI run), and the last job, will trigger the next
build.
There's no better way at the moment to do this, without re-factoring the
entire `.travis.yml` file to work with build-stages (a new feature that's a
bit of work to get working properly with our current setup).
=> .travis.yml,CI/travis/after_deploy: trigger other builds after libiio

.travis.yml, CI/travis/before_install_linux, CI/travis/inside_bionic_docker.sh, CI/travis/inside_centos_docker.sh, CI/travis/make_linux
Some of the code added for the CentOS dockers and the Ubuntu Bionic docker looks a bit too quirky/workaround-y.
These changes remove some of those hacks, making the code pretty.
The end-goal here is re-usability, as some of this code is intended to run for `libad9361-iio` and other projects along the pipeline.
=> CI/travis: cleanup docker & CentOS quirks

CI/travis/lib.sh
This seems to have slipped through after doing a few rebases.
I've fixed it a few times on local branches.
The SFTP script did not error out, so that's why it wasn't caught there.
=> CI/travis/lib.sh: fix dangling quote in symlink command

CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_linux
We want to re-use the docker logic in other repos (e.g. libad9361-iio).
We need to lib-ify that logic, since we won't download `make_linux` and
`before_install_linux` and similar files.
=> CI/travis: lib-ify docker logic

CI/travis/lib.sh
These errors only show up when the script gets deployed via wget.
They don't interfere with libiio's build.
=> CI/travis/lib.sh: shell parsing errors

CI/travis/after_deploy, CI/travis/before_deploy, CI/travis/before_install_darwin, CI/travis/before_install_linux, CI/travis/deploy, CI/travis/inside_docker.sh, CI/travis/lib.sh, CI/travis/make_darwin, CI/travis/make_linux
We can avoid downloading artifacts to see if they exist or now. This saves
a bit of time and some bandwidth. If we just do a `rm` command via SFTP
and allow it to fail, this should be just as good.
The `sftp` command is also wrapped into it's own function, to unclutter
some of the SFTP logic.
=> CI/travis/lib.sh: rework artifact removal via SFTP

CI/travis/lib.sh
This allows other scripts to specify a different build directory where
the scripts (that get downloaded) will be placed.
=> CI/travis/lib.sh: make the build dir configurable

.travis.yml
Builds for Xcode 8 take up about 30+ minutes.
The build also reports:
```
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
```
Maybe it's a good time to remove.
=> [RFC] build,.travis.yml: drop xcode 8 build

CI/travis/jobs_running_cnt.py
Previously we were just counting `started` states, but it seems that
Travis-CI has a `created` state for jobs, which is before the `started`
state.
This means some builds were triggering before the entire job group would
finish.
=> CI/travis/jobs_running_cnt.py: count `created` states as well

CI/travis/inside_docker.sh
Some repos will have a lowercase `ci` dir.
The `inside_docker.sh` should handle them as well.
=> CI/travis/inside_docker.sh: handle lowercase `ci` dir

CI/travis/jobs_running_cnt.py
Travis CI has multiple job states to account for (queued, received, etc).
In some conditions, the number of created + started == 1, which typically
happens during multiple Travis-CI builds running.
It's also hard to say "job[state] not in [list states]" since there are so
many job states to account for. So we try to account for the ones we could
identify so far.
Travis' API docs are not that great either. They claims it's
self-documenting. Oh well...
Links:
https://docs.travis-ci.com/user/developer/#api-v3
https://developer.travis-ci.com/resource/jobs#Jobs
=> CI/travis/lib.sh: fix triggering multiple builds

context.c
This algorithm should be backwards compatible
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> sorting: Use old sorting algorithm for channels

.travis.yml, CI/travis/before_install_linux, CI/travis/make_linux_qemu, CI/travis/setup_qemu_for_arm.sh
This adds a two more distributions to the build matrix : raspbian jessie and  raspbian stretch.
This should also provide a basic framework for those non-native travis-ci architectures in the future that we may want to support.
=> travis-ci: enable raspberry on qemu inside travis-ci 

iiod/usbd.c
=> iiod: usbd: Fix wrong null pointer check

local.c
This should fix coverity issue:
```
*** CID 343595:  Memory - illegal accesses  (STRING_NULL)
/home/travis/build/analogdevicesinc/libiio/local.c: 1090 in local_get_trigger()
1087             nb = dev->ctx->nb_devices;
1088             for (i = 0; i < (size_t) nb; i++) {
1089                     const struct iio_device *cur = dev->ctx->devices[i];
>>>     CID 343595:  Memory - illegal accesses  (STRING_NULL)
>>>     Passing unterminated string "buf" to "strcmp", which expects a null-terminated string.
1090                     if (cur->name && !strcmp(cur->name, buf)) {
1091                             *trigger = cur;
```
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> local.c: make sure dst is null-terminated if fread fails

appveyor.yml, bindings/python/CMakeLists.txt, bindings/python/setup.py.cmakein, libiio.iss.cmakein
- Add an option in the libiio installer to install Python bindings.
- Add Python bindings installers for Python 3.7 and 3.6 in the archive.
- Add csharp bindings in the archive.
=> General: Rework the Windows installer and the zip artifact.

network.c
It turns out that resolving interface name from
`sockaddr_in6->sin6_scope_id` only works on link-local addresses. This
resulted in errors when connecting to iiod over global ipv6 (see #296). This PR fixes that.
I have not been able to test this on WIN32, but I have found multiple
pieces of win32 code using this macro, which all seem to pull it from
`<ws2tcpip.h>` which is already included in network.c so I'm confident it
will work.
=> Network: Only resolve interface name on IPv6 link-local addresses

utilities.c
__MACH__ is added to exclude iOS as it hasn't been tested whether iOS has locale support or not.
=> utilities.c: Consider OS X a platform that has locale support

CI/travis/before_install_darwin, CI/travis/lib.sh
Previously, they were being installed. And if they were already installed
we would have upgraded them, which takes quite some time.
On older OS X versions, this can take too much.
So, just install packages only if they aren't already.
=> build,ci: os-x: install packages if they don't exist

CI/travis/lib.sh
The issue only shows up when using the `brew_install_if_not_exists`
function, because that one checks if the package is installed first, and
only then installs it.
`brew ls --version` also seems to be valid, but it looks like it prints
`brew Version` and exits successfully.
For this check, we only need `brew ls`, but using `brew list --versions`
also prints in the log the current installed versions, which is useful when
debugging.
=> ci,lib: fix typo; correct is `brew list --versions`

bindings/python/CMakeLists.txt
CMake python bindings: use "find_package (Python) COMPONENTS Interpret)" instead of deprecated "include(FindPythonInterp)"
Signed-off-by: Matej Kenda <matejken@gmail.com>
=> CMake python bindings: "use find_package (Python)"

examples/ad9361-iiostream.c
The example now takes command line arguments to select local context vs uri context. Also added a couple of comments on usage. This update is because of some EZ questions where users run this example on host computer and naturally, find that the example fails to create default context.
=> A minor update to ad9361_iiostream.c example

CI/travis/lib.sh
Whenever running `brew install` and `brew cleanup` hasn't been run for 30
days, `brew cleanup` will be run.
For Travis-CI's OS-X images, this is often true, which just consumes time.
Travis-CI has an opt-out env-var `HOMEBREW_NO_INSTALL_CLEANUP` which
disables this behavior when set.
Most about it here:
https://github.com/Homebrew/brew/pull/5472/commits/8144667a718f8f1afead3efa74c97d28dbc82c63
`libiio` is not affected by this default `brew cleanup` behavior (yet).
However, since these scripts are propagated in other repos, then it makes
sense to have this behavior default here.
=> ci,os-x: disable brew's default install cleanup

bindings/python/CMakeLists.txt
=> gh-327: Use "include(FindPythinInterp)" when compiling with CMake older than 3.12

examples/dummy-iiostream.c
Fixes to the dummy-iiostream example.
=> Fixes #303 and #302

bindings/python/iio.py
Fixed loading of libiio on non-Windows systems where find_library shall find it in the path if the specified name is 'iio'.
Fixes error when importing module iio on Linux. 
Signed-off-by: Matej Kenda <matejken@gmail.com>
=> Python: Fixed loading of libiio on non-Windows systems 

tests/iio_attr.c
With the right compiler flags we get:
./tests/iio_attr.c:529:11: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]
since the code looks like: "if (wbuf && !wbuf)"
This patch removed the offending/dead lines.
=> Fix #325, remove dead code/compiler warning

CI/travis/lib.sh
Some of Travis-CI integration uses quite a few Github API calls.
It's useful to print them to better understand what's happening, when
things are not happening as expected.
=> ci,lib.sh: print Github API rate limits

CMakeLists.txt
Previously, building libiio on FreeBSD would warn with:
network.c:240:8: warning: implicit declaration of function 'pipe2' is invalid in C99
This fixes that, since pipe2 (inside <unistd.h>) is protected by __BSD_VISIBLE. 
On Linux, it's protected by _GNU_SOURCE (which is already defined in the cmake).
=> fix #336, remove warnings on FreeBSD

CMakeLists.txt, usb.c
FreeBSD doesn't call it libusb-1,0 like linux does - it calls it libusb
and just installs it into /usr/include/*, not /usr/include/libusb-1.0/*
like Linux, Apple and Windows does... so handle these differences.
Tested on FreeBSD 12.1 (Release) & Debian 10 (Buster)
Signed-off-by: Robin Getz robin.getz@analog.com
=> Fix #336, make sure libusb can be found on FreeBSD variants

CI/travis/make_darwin, CI/travis/make_linux, CMakeLists.txt, appveyor.yml, bindings/CMakeLists.txt, bindings/csharp/CMakeLists.txt, bindings/matlab/CMakeLists.txt, bindings/python/CMakeLists.txt
Many distributions have patches to change the CMake to turn off bindings
This internalize that to the upstream package in a sustainable manner.
The flags default to on, so it will not change the default behaviour.
Flag names are borrowed from libm2k
=> Add Cmake flags to turn on/off bindings

iio.h
Previously, one would have to check source code to determine URI
types and address part formatting.
Signed-off-by: Edward Kigwana <ekigwana@gmail.com>
=> Improve URI Documentation for iio_create_context_from_uri

local.c
Signed-off-by: fpagliughi <fpagliughi@mindspring.com>
This probably isn't a complete solution for release, but does seem to fix the limited case of some differential channels. I also wasn't sure when some attributes might be private (if I should look for a special case to return 2).
=> #352 Match global attributes for differential channels.

bindings/csharp/IOBuffer.cs
- Change the IntPtr cast to long instead of int. (issue #153 )
IntPtr is a platform specific type and is expected to have different
values on 32-bit or 64-bit systems. In C#, int is a 32-bit signed integer,
while a 64-bit integer is represented as long.
- Add missing read() functionality to IOBuffer (issue #154 )
Signed-off-by: Alexandra.Trifan <Alexandra.Trifan@analog.com>
=> bindings/csharp: IOBuffer.cs: Add missing read() functionality and fix type casting.

local.c
This PR solves #190 
Verify that the kernel does not return a buffer smaller than the number of bytes that are requested.
Issue: a call to iio_buffer_push_partial() right after creating the buffer with a small number of bytes, fails with -EFBIG.
This fixes that.
=> local: Fix the checking of the buffer size returned by kernel

tests/iio_readdev.c
The captured data is sent to stdout but during this process (on Windows)
any byte that has the same value as line feed character (LF) gets
converted to CF-LF characters. This dissrupts the alignment of bytes
that represent the samples of the device.
=> iio_readdev: Fix corrupt data that was being captured on Windows

channel.c
Channel whose ID is "timestamp" has type IIO_CHAN_TYPE_UNKNOWN
before this patch, but it should be IIO_TIMEOUT.
=> Handle channel IDs without index or modifier correctly

tests/iio_info.c
This applies the same fix as cc9b3c7 to iio_info, which fixes some
issues on AD936x based devices, which were giving:
attr  9: gain_table_config ERROR: Input/output error (-5)
Now gives the correct data:
attr  9: gain_table_config value: <gaintable AD9361 <snip>
This was discussed in #268
=> iio_info: use malloc rather than stack buffers

tests/iio_info.c
A few issues (#366, #373)  have popped up recently when
iio_channel_get_type(ch) == IIO_CHAN_TYPE_UNKNOWN
This helps bring that to the top by easily notifing kernel developers
when they are doing things that aren't understood by the library.
=> iio_info: warn when iio_channel_get_type = IIO_CHAN_TYPE_UNKNOWN

usb.c
This outputs more text, so (hopefully) end users can diagnose their own
errors/issues.
=> usb: be more verbose on errors, by using iio_strerr

.travis.yml
Mathworks no longer supports macOS 10.12
https://www.mathworks.com/support/requirements/matlab-system-requirements.html
```
Operating Systems
macOS Catalina (10.15)
macOS Mojave (10.14)
macOS High Sierra (10.13.6)
Note:
macOS Sierra (10.12) is no longer supported.
On macOS High Sierra, version 10.13.6 is required.
```
Travis-CI's Xcode + macOS matrix lists Xcode 9.4 (only) running on macOS
10.13 and all Xcode10 running on 10.13.
All other XCode 9 versions only support 10.12
https://docs.travis-ci.com/user/reference/osx/#macos-version
We can suggest that people upgrade their Xcode to version 10. It's also
likely that most people running macOS 10.13, are running Xcode 10 already.
In any case, we can start to consider dropping the Xcode9 build to reduce
the overall build-time.
Signed-off-by: …
=> ci,build: drop xcode9 build

network.c
Don't make errno positive by accidently flipping the sign
This turns iio_strerror() from this:
Unable to create IIO context Unknown error -110 (110)
into:
Unable to create IIO context Connection timed out (-110)
=> network: errno should be already negative

iiod-client.c
printf("zu") is for unsigned size_t, not ssize_t (which is signed)
Since all error codes are negative - the current code prints out
a unsigned version, which is wrong.
This fixes that.
=> iiod-client: errors are negative, so print them that way

usb.c
This fixes #384
I think this was just missing, and will be necessary as we do
more IMU/accelerometer devices on RPi.
=> usb: Add trigger support to the USB backend

tests/CMakeLists.txt, tests/iio_stresstest.c
This is based on an iiod robustness test that Lars did:
https://github.com/analogdevicesinc/libiio/commit/dc337057506507c35ab7185af810048eb2e69259
This cleans things up, adds a few more options.
On 2018R1 release (ZedBoard + FMCOMMS3) would cause kernel panics (Scheduling
while atomic) in a few hours over ethernet.
On 2019 release (same hardware), can run for 3 days, doing 45 context
open/destroy per second. (over 11M in total, & 128k where the open/close
was simultaneous in different threads).
Output looks like:
total: 2d21h31m21s Context : 11510707 (45.99/s), buffers: 57504276 (229.76/s), refills : 287540521 (1148.87/s)
0        :  128395 ( 1.12%)
1 - 9   μs :  338154 ( 2.94%)
10 - 99  μs :  466087 ( 4.05%)
100 - 999 μs : 1155429 (10.04%)
1 - 9.9 ms : 2774553 (24.10%)
10 - 99  ms : …
=> add a stresstest tool for rapid connects and disconnects for iiod

network.c
Reverts analogdevicesinc/libiio#382
This was a problem in the application, not the library.
The man page for errno states:
Valid error numbers are all positive numbers
The semantics used is `ret` is negative, and errno should be positive.
=> Revert "network: errno should be already negative"

CI/travis/before_install_linux, CI/travis/make_darwin, CI/travis/make_linux
Fixes #398 
For some reason, doing `make && make package` doesn't seem to yield a
compiler/build error on Linux.
This may be due to how '/bin/sh' interprets command concatenation via '&&'.
Splitting the make commands seems to help.
See:
https://travis-ci.org/github/analogdevicesinc/libiio/builds/661401114
This is essentially branch 'rgetz-review-zeroconfupdates' rebased with this
change.
=> ci,build: split 'make && make package' commands

examples/Makefile, examples/dummy-iiostream.c, examples/iio-monitor.c, iio.h, man/make_man.sh, tests/CMakeLists.txt, tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_writedev.c
I was starting to look at #263 (which I read as report more errors, better, so users can diagnose things themselves).
I thought I would start with the "more errors" first.
not 100% sure this is a good idea or not. It will ensure that people who use it - always check their return values. (that's when/if it gets used), and hopefully experience less issues using the library. I have not tried compiling osc with this yet... (and am a little afraid to).
Would like to get @dNechita & @pcercuei & @commodo & @tfcollins opinion.
=> warn when ignore return vals

CMakeLists.txt, tests/iio_stresstest.c
- "warning: implicit declaration of function 'sysctlbyname' is invalid in C99"
- "error: unknown type name 'u_int'" after including <sys/sysctl.h>
Signed-off-by: Matej Kenda <matejken@gmail.com>
=> Fixed warnings on MacOS

Doxyfile.in, mainpage.dox
After spending a couple days looking at other people's Doxygen,
properly set up the utilities to act as "examples" for people
to look at. Also, set the "tree" so a side menu appears.
=> Doxygen: add examples to our Doxygen

tests/iio_writedev.c
The help text for iio_writedev was original copied from iio_readdev. There
is a small copy&paste error for the size parameter description which
reference a "capture buffer" while for iio_writedev it should be "transmit
buffer".
=> iio_writedev: Fix copy&paste error in size parameter help

tests/iio_readdev.c, tests/iio_writedev.c
Currently when calling iio_readdev on an output device or iio_writedev on an input device they'll happily enable all channels and try to start capturing/transmitting from/to the device.
Add checks that make sure the channels that have the incorrect direction are ignored by the two tools. This makes sure that they'll error out with an appropriate error message rather.
This also future-proofs the tools for a time when there might be devices with both input and output channels.
=> iio_{read,write}dev: Skip channels with the wrong direction

examples/Makefile, examples/ad9361-iiostream.c, examples/ad9371-iiostream.c, examples/adrv9009-iiostream.c, examples/dummy-iiostream.c, examples/iio-monitor.c
and clean up the resulting errors. This resolves a few codacy issues
that have been lingering for awhile. There shouldn't be any functional
changes from these. I tested most, but not all, since they were all
pretty similar.
=> examples: Add -Wextra & -pedantic-errors to the example Makefile

CI/travis/check_kernel.sh, CI/travis/make_linux
As discussed in #392 and #396, this adds a small shell script which
downloads the kernel's iio header file, and checks channel types and
channel modifiers to make sure we aren't falling behind.
This will be checked once per Travis-CI build, and takes about 0.5 seconds.
=> check kernel's headers against libiio headers in CI

CMakeLists.txt, Doxyfile.in, dns_sd.c, dns_sd_avahi.c, dns_sd_bonjour.c, iio-private.h, network.c, network.h, scan.c
This makes dns-sd work on Linux and MacOS for scan contexts. This still needs a Windows implementation. 
On MAC:
```
analogs-mini:build analog$ ./tests/iio_info -s
Available contexts:
0: 192.168.86.35 (ad7291-ccbox,ad9361-phy,xadc,cf-ad9361-dds-core-lpc,adis16460,cf-ad9361-lpc) [ip:analog-2.local.]
```
on Linux (different network):
```
getz@brain:~/github/libiio$ ./build/tests/iio_info -s
Library version: 0.19 (git tag: d5b4247)
Compiled with backends: local xml ip usb serial
Available contexts:
0: 0456:b673 (Analog Devices Inc. PlutoSDR (ADALM-PLUTO)), serial=104473222a87000618000600473ed57ae0 [usb:3.28.5]
1: 192.168.1.120 (ad7291,ad9361-phy,xadc,cf-ad9361-dds-core-lpc,cf-ad9361-lpc) [ip:analog.local]
```
This should also resolve #391
=> dns-sd (avahi/bonjour) improvements

CI/travis/inside_docker.sh, CI/travis/lib.sh
This mechanism has been roughly adapted from the way it's done for the
Linux build.
A file is used on the mount-point that is passed to the docker, and the
'inside_docker.sh' script will load it if found.
Also added 3 common/variables. Two of them are used in the Linux build.
=> ci,build: add generic mechanism for passing some Travis-CI envs

CI/travis/make_linux
This is a small tweak to try to reduce the travis-ci noise
today, we get errors like:
running install
Traceback (most recent call last):
File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 89, in <module>
setup(**config)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 43, in run
self._check_libiio_installed()
File "/home/travis/build/analogdevicesinc/libiio/build/bindings/python/setup.py", line 66, in _check_libiio_installed
raise Exception(msg)
Exception: The …
=> travis-ci: Do a make install so libiio is on system path

.travis.yml, CI/travis/before_install_linux, CI/travis/lib.sh
Ubuntu 20.04 should be out in a couple of weeks. But docker images are
currently available.
Start using them.
Also, Ubuntu 20.04 seems to start phasing out some Python2 stuff, so we
need to install python3-pip vs python-pip.
We'll still keep python-pip for older distros, until Ubuntu 20.04 is old
enough.
=> ci,build: add Ubuntu 20.04 docker builds 

debug.h, dns_sd.c, dns_sd_avahi.c, dns_sd_bonjour.c, iiod-client.c, iiod/iiod.c, iiod/ops.c, iiod/parser.y, iiod/usbd.c, local.c, network.c, serial.c, usb.c, xml.c
this namespacing will help avoid collisions like #425 on Windows
and other platforms, that libiio is compiled on.
=> fix #425: add IIO_ prefix to INFO, WARN, DEBUG and ERROR macros

dns_sd.c, iiod/iiod.c, tests/iio_stresstest.c
fix the remaining outstanding/recently added coverity issues, and one that has been there for awhile.
=> coverity fixes2

libini/libini.c
ftell can return -1 on error, and we were not looking
for that before using that with malloc().
Check for the negative return value.
=> coverity: fix Argument cannot be negative in libini

tests/iio_stresstest.c
make sure to apply limits to all input from user arguments.
I think this is the last coverity issue from recent commits.
=> coverity: fix Untrusted value as argument in iio_stresstest

tests/iio_stresstest.c
According to a few places I found, the passing an argc to strtoul
without checking it's length first, will cause this error to be flagged,
so check the length.
Hopefully this finally resolves things.
=> coverity: iio_stresstest : fix Untrusted value as argument (TAINTED_SCALAR)

tests/iio_writedev.c
The bug was described in this pull request:
https://github.com/analogdevicesinc/libiio/pull/410
As @commodo suggested, the old solution was a little confusing for future development because it forced the while loop to do an extra iteration in order to find out that all requested samples were sent.
The modifications from this pull request avoid this thing to happen. Instead of calling quit_all(), which also closes the buffer, after reading from stdin the requested number of samples, the program now only sets app_running and exit_code. Therefore the program will now push even the last buffer, which was not pushed in the previous version, and afterwards will exit the while loop.
If the cyclic mode is enabled, app_running should not be set on false in order to enter the while loop which …
=> iio_writedev: fix off by one when pushing buffers bug

CMakeLists.txt, man/CMakeLists.txt
I noticed that empty `CMakeFiles` directories are installed into the man page directories:
```
$ DESTDIR=/tmp/libiio/ ninja -j1 install
[snip]
-- Installing: /tmp/libiio/usr/share/man/man3
-- Installing: /tmp/libiio/usr/share/man/man3/libiio.3
**-- Installing: /tmp/libiio/usr/share/man/man3/CMakeFiles**
-- Installing: /tmp/libiio/usr/share/man/man1
-- Installing: /tmp/libiio/usr/share/man/man1/iio_attr.1
-- Installing: /tmp/libiio/usr/share/man/man1/iio_writedev.1
**-- Installing: /tmp/libiio/usr/share/man/man1/CMakeFiles**
-- Installing: /tmp/libiio/usr/share/man/man1/iio_readdev.1
-- Installing: /tmp/libiio/usr/share/man/man1/iio_info.1
-- Installing: /tmp/libiio/usr/share/man/man1/iio_reg.1
[snip]
```
First patch is a non-functional change to simplify the cmake file by using `foreach`, …
=> cmake: man: Avoid installing empty directories

bindings/python/iio.py
Added the missing Python bindings. More details about these can be found in this [discussion](https://github.com/analogdevicesinc/libiio/issues/365).
=> python: added missing Python bindings.

channel.c, context.c, device.c, iio-private.h, utilities.c
This is a follow on from #439 
It slowly updates some of the core files in a way that should be easier to review, and follow, and bisect. Since this effects the way that the internal xml is built up, one file at a time is changed, the downsides is there are 10 commits in the PR.
- It tracks the length of building up xml files
- adds a iio_strlcpy
- uses things, so there is no chance of undetected buffer overflow
- optimize things to use memcpy where possible.
I will apply the other changes that were in the old branch if/when this gets accepted. That would removes these: 
- 7 instances of `snprintf` (should be using `iio_snprintf`)
- 2 instances of `sprintf`(should be using `iio_snprintf`)
- 8 instances of `strncpy` (should be using `iio_strlcpy`)
- 1 instances of `strcpy` (should be using …
=> remove strcpy

debug.h
According to https://cwe.mitre.org/data/definitions/134.html describes
functions that accepts a format string as an argument, but the format
string originates from an external source as dangerous.
This gets tagged on all the IIO_DEBUG, IIO_INFO, IIO_WARNING, and
IIO_ERRRO functions that are in debug.h However, they are always called
internally from the library, have fixed format strings and can not be
modified externally, so mark them as safe.
=> flawfinder: mark some ignores for CWE-134 in debug.h

dns_sd.c, iiod/iiod.c, iiod/ops.c
https://cwe.mitre.org/data/definitions/120.html points out that
sprintf will overflow buffers, so don't use it.
We move to the internal iio_snprintf, and move a few remaining snprintf
to the same to handle the necessary windows/Linux differences.
=> flawfinder : sprintf doesn't check for buffer overflows.

.prospector.yml
In a few of the recent python commits, @cristi-iacob was running into issues about the pep257 tool complaining when lines were inserted, and then when they were not. I checked into it, and this should resolve things.
The pep257 tool (part of prospector) has two rules:
D203: 1 blank line required before class docstring
D211: No blank lines allowed before class docstring
Which conflict, so turn D203 off.
=> prospector: add a configuration file for prospector

.travis.yml, CMakeLists.txt
The current Cmake logic is set so that if things (like avahi) are not
installed, it doesn't build or link against it. On normal systems this
make sense.
I recently noticed that coverity builds (which happen on the coverity
servers, not on the Travis-CI servers), don't have external libraries
installed, and then a few options don't get configured/added, and
therefore, don't get checked.
Add an option to the Cmake which blindly adds things (which is fine,
since coverity doesn't actually compile/link things); so all backends
and options get checked.
=> Cmake/Coverity: Force coverity to check _everything_

channel.c, context.c, device.c, iio-private.h
be more pedanic about the differences between strlen (doesn't include
null char) and sizeof (which does include null char).
Now, we calculate the exact length the the string (number of char)
add one for malloc, fill everything out, and then check it make sure
the length is one (the null char) left.
tested on host and local (Zedboard + FMCOMMS2)
=> xml buildups: fix bug introduced by recent changes

.prospector.yml
Pylint is officially supported in Codady on its own. Since we  want better
configurability, disabling Pylint in Prospector and using the standalone
"Pylint" tool in Codacy.
=> Prospector: turn off pylint

examples/ad9361-iiostream.c, examples/ad9371-iiostream.c, examples/adrv9009-iiostream.c
Since we are ensuring (to secure or guarantee:) something happens -
change the ASSERT macro to that name, so all the tools (Coverity?) that look for
ASSERTs will not flag this by accident.
Changes IIO_ASSERT to IIO_ENSURE
=> Coverity: 'IIO_ASSERT' falsely flags just like 'ASSERT' does. Change it.

examples/dummy-iiostream.c
dummy-iiostream was still using the standard assert, so remove that and
replace it with the default macro that is being used in the other files.
=> Coverity: Remove remaining asserts that were not caught

tests/iio_common.c
When common functions were made, a bug in the logic made it so the wrong
info was printed out the list when we were scanning for contexts.
slipped in, due to only testing with two devices (not just one).
=> iio_info: fix scanning

bindings/csharp/Attr.cs, bindings/csharp/Channel.cs, bindings/csharp/Context.cs, bindings/csharp/Device.cs, bindings/csharp/IOBuffer.cs, bindings/csharp/Trigger.cs, bindings/csharp/examples/ExampleProgram.cs
According to Microsoft, and Sonar C#, all Control structures (do, for,
foreach, while, if) should use curly braces. While not technically incorrect,
the omission of curly braces can be misleading, and may lead to the
introduction of errors during maintenance.
See CERT, EXP19-C Use braces for the body of an if, for, or while statement
https://www.securecoding.cert.org/confluence/x/1QGMAg
See CERT, EXP52-J Use braces for the body of an if, for, or while statement
https://www.securecoding.cert.org/confluence/x/3wHEAw
=> csharp: Control Structures should use curly braces {}

tests/iio_readdev.c
in iio_readdev:
206    size_t sample_size;
...
354    sample_size = iio_device_get_sample_size(dev);
...
404    num_samples -= read_len / sample_size;
There are two issues:
iio_device_get_sample_size can return negative error codes,
and we would miss these. Fix that by making it a signed number.
this could potentially cause an error if sample_size is zero.
Catch that fault and error out. While we are here, check
for negative error codes, and also error out.
Reported by Coverity.
=> Coverity: Fix potential divide by zero in iio_readdev

appveyor.yml
Otherwise it might fail because pacman can't unzip .zst files or because local packages are outdated.
=> appveyor.yml: Upgrade packages and pacman before trying to install any dependencies.

CMakeLists.txt
In the past Clang was not set on x86, and now we also print a warning if
we don't know what the compiler is.
=> cmake: Restructure CMake CFLAGS for and ensure they are set

local.c
when moving to iio_strlcpy in local.c during:
3f305ee3f0ada31d4d26ac97f349912869825cfe
we were off by one, so fix that.
Tested over network from FMCOMMS2/Zed Board (running Master) to Windows
(running 0.19 release).
=> local.c: fix off by one introduced in 3f305ee

CMakeLists.txt, buffer.c, channel.c, context.c, device.c, iio-config.h.cmakein, iio-private.h, iiod-client.c, local.c, network.c, tests/CMakeLists.txt, tests/gen_code.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_writedev.c, usb.c, utilities.c, xml.c
to bring the Windows builds to the same as the other CI infrastructure.
=> cmake: Add MSVC flags for Wall, Wno-sign-compare and Werror

CMakeLists.txt, channel.c, context.c, device.c, dns_sd.c, iiod/CMakeLists.txt, iiod/ops.c, local.c, tests/iio_stresstest.c, usb.c
With all the coverity and codacy updates, there are very few signed/unsigned issues anymore - so fix those up, and remove the ignore flag.
This will need to be re-based on master after #466 is merged.
=> Dont ignore sign differences

tests/iio_attr.c, tests/iio_common.c
With this add and fix, iio_attr supports triggers better (which show up on 2019R1).
=> fix iio attr so it supports triggers better

bindings/python/README.md
As reported in this issue #479, I have added a README.md file which contains information to be displayed on the main Pypi libiio page.
=> python: added README.md file for Python bindings.

bindings/python/iio.py
Add abstract methods to attribute base class in python bindings. This
should fix certain codacy errors.
=> Enforce method implementation in bindings

bindings/python/iio.py
Fix pylink warnings related to abstract methods and simpler attribute
name check.
=> Fix E1101 and R1714 pylint warnings

CI/travis/make_linux, CMakeLists.txt, iiod/CMakeLists.txt
when we turned on -Werrors too soon, it would cause issues like this:
./build/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
./build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:11: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
return ((int*)(&libusb_get_version))[argc];
^
cc1: all warnings being treated as errors
The problem being that this isn't an error, but -Wpedantic and -Werror
cause it to be one. So, we shuffle down the place in the Cmake where we
set the -Werror, and shuffle up where we look for check_symbol_exists().
While we are here, we also cat the CMake error log on the CI to help
debug issues like this in the future.
=> Cmake: move where -Werrors are turned on in the Cmake

tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
Some (older) implementations of getopt_long) do not protect against internal
buffer overflows, so copy argv to a temp str array, and parse most in a
common function. (-u -h -x -n, and -S).
-h, --help Show this help and quit.
-x, --xml  Use the XML backend with the provided XML file.
-u, --uri  Use the context at the provided URI.
-S, --scan Scan for available backends.
-a, --auto Scan for available contexts and if only one is available use it.
The "default" for scan is "S", since "s" is used for many apps as sample
size. This means that iio_info now takes -s and -S as scan.
This also fixes both CWE-120 and CWE-20
https://cwe.mitre.org/data/definitions/120.html
https://cwe.mitre.org/data/definitions/20.html
and almost is a net decrease (348 insertions, 345 deletions over 9
files). …
=> tests: add a common function to parse and create iio_contexts

examples/iio-monitor.c, iiod/ops.c, tests/iio_stresstest.c
The usleep() function is considered obsolete. The interaction of this function
with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(),
and nanosleep() is unspecified (CWE-676)
https://cwe.mitre.org/data/definitions/676.html
So move to nanosleep() instead.
=> remove usleep(): usleep() is considered obsolete, move to nanosleep()

dns_sd.c
After a loop finishes (normally by a 'break;') only print out
the IIO_ERROR message if there was an error (was no 'break;').
This resolves some random message printing out:
ERROR: dnssd_remove_node call when 1 exceeds list length (1)
when doing dns-sd (iio_info -s).
=> dns_sd: qualify IIO_ERROR message before it prints out

CI/travis/make_linux, bindings/python/CMakeLists.txt, iio.h
Now that docs are building on CI, check for warnings/errors, and fail on CI if necessary.
=> make doc errs fail on ci

doc/index.html.in
=> html: Remove repetitive words

tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
Not sure why, but it looks like cppcheck doesn't run on pull requests...
When adding : 336c3c8b884d83049b589ecd8b1482076d40e6e6
I made a mistake, and called xmalloc() with a NULL name, which is
printed when malloc fails. So:
- fix the calling functions to include a name
- add a check to make sure name isn't touched when if it is NULL
This should resolve things.
=> cppcheck: fix null ptr dereference

iio.h, serial.c
in the past the serial backend was limited to a single stop bit, when
most hardware can support one or two. This allows URIs to define the
number of stop bits in a standard notation (8n1). This means serial uri
are now defined as:
serial:port,baud,config
serial:/dev/ttyUSB0,115200,8n1
This does break backwards compatibility with the previous serial URI
which was:
serial:/dev/ttyUSB0,115200n8
Since this is outside the library, and there are few serial users, and
8n1 is the "standard" way of doing things - it's better to change/update
now.
Update the doc (which mistakenly said we supported this).
=> serial: support defining number of stop bits in serial URI

tests/iio_attr.c
When helping debug someone's shell scripts what used iio_attr on
Friday, we noticed that iio_attr just plain eats too many things,
which makes it hard to debug things when using -q (quiet).
So, make sure to print things when errors occur. Errors are now defined
as attempting to read/write a device/channel/buffer/attribute that
doesn't exist. or when a write error occurs.
Also exit with an exit error code, so that if you set -e in a shell
script, it quits right away.
=> iio_attr: add error checking

.pylintrc
too-many-instance-attributes (R0902):
Too many instance attributes (7) Used when class has too many instance
attributes, try to reduce this to get a simpler (and so easier to use) class.
Many of our functions have 8 or more, so turn this off.
too-few-public-methods (R0903)
Too few public methods (%s/%s) Used when class has too few public methods,
so be sure it's really worth it.
Many of our classes have 0 public methods due to the way that our C is
imported.
=> pylint: turn off some checks

.prospector.yml, bindings/python/examples/iio_info.py
convert tabs to spaces
run black
fix pylint issues
- variable name too short
- import order
- docstring missing
run black again
=> iio_info.py: update to black and fix pylint issues

local.c, xml.c
Flawfinder reminds us that unless checked, the resulting number can exceed
the expected range (CWE-190). If source untrusted, check both minimum and
maximum, even if the input had no minus sign (large numbers can roll over
into negative number; consider saving to an unsigned value if that is
intended).
https://cwe.mitre.org/data/definitions/190.html
replace these library calls with strtoll and strtof, and include more
error checking.
=> Flawfinder : remove atol and atof, replace with strtoll and strtof

.prospector.yml, bindings/python/examples/iio_info.py, bindings/python/examples/iio_readdev.py, bindings/python/examples/iio_writedev.py, bindings/python/iio.py
This resolves most pylint and pep8 and pep257 issues pointed out via
prospector pylint and should be formatted according to black.
prospector --profile .prospector.yml ./bindings/python/examples/iio_info.py
pylint --rcfile=.pylintrc ./bindings/python/examples/iio_info.py
black ./bindings/python/examples/iio_info.py
There are still some issues with the way that globals are handled, but I
think it is OK for now, and makes the generated doc look better as
well.
=> pylint & pep257: Resolve issues in python coding style.

appveyor.yml
Issue: https://github.com/msys2/MSYS2-packages/issues/1967
Signed-off-by: AlexandraTrifan <Alexandra.Trifan@analog.com>
=> appveyor.yml: Fix MSYS2 pacman install. Don't use the latest version.

context.c, local.c, network.c, serial.c, usb.c
The uri context attribute is added as "local:" (which is what is in iiod), and as this is passed to various remote devices, it will be overwritten by the remote method (usb, ip or serial).
-Robin
=> add uri context attribute

iio-private.h, usb.c
per #508, a windows header (combaseapi.h) includes this:
making 'interface' a keyword, which we need to avoid using, so - avoid
using it to ensure things compile without issues.
=> usb.c : avoid using 'interface' as an identifier.

usb.c
Despite the fact that #512 passed all checks, master got broken.
Looks like the checks don't include the usb part of the library.
=> usb: Fix compile error caused by unkown indentifier (interface)

local.c
In the past, when doing an 'iio_info -s' on machines with local contexts,
you would get something like:
"Local devices"
which isn't exactly descriptive...
look in sysfs for the machine (DT model for embedded ARM and DRI for x86),
and combine that with a device list so now you get something that looks like:
Available contexts:
0: (spi1.0, ad9361-phy, cf-ad9361-lpc, spi1.1, xadc, ad7291, cf-ad9361-dds-core-lpc on Xilinx Zynq ZED) [local:]
or
Available contexts:
0: (ad7124-4 on Raspberry Pi 4 Model B Rev 1.1) [local:]
which makes it easier to identify for end users.
=> local: add some more info to local scan contexts

channel.c, device.c, examples/iio-monitor.c, iiod-client.c, iiod/iiod.c, iiod/lexer.l, local.c, network.c, serial.c, tests/iio_common.c, usb.c, utilities.c, xml.c
a recent change that we (I) made to things wasn't handling
under|over-flows properly. The man page for strtol states:
Since strtol() can legitimately return 0, LONG_MAX, or LONG_MIN on both
success and failure, the calling program should set errno to 0 before the
call, and then determine if an error occurred by checking whether errno
has a nonzero value after the call.
So do that - set errno to 0, and see if it is errno is set to ERANGE
when it's finished.
Review the entire code base, and do the same thing everywhere.
=> coverity: handle strtol and strtoll under|over-flows properly

network.c
the buffer 'uri' was malloced, and only free'd on the error case.
free it in the normal case.
=> coverity: fix resource leak in network.c

bindings/python/setup.py.cmakein
This should fix #497 by setting up the python specific README.md
=> python: point to the new README.md

iio.h, scan.c, tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
allow multiple backends in the scan context
=> allow multiple scan backends

tests/gen_code.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_info.c
Now that we have the uri in the context, we use it, which simplifies the
codegen, and ensures that things work with both local and remote contexts.
This fixes #529
=> iio_attr: enable code gen for local contexts

tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
the rework and moving to common functions for argument parsing broke a
few things, since I thought that you could pass a incomplete optstring
and incomplete longopts to getopt_long(). However, this is not the case.
It broke long flags (--uri vs -u) and broke the position parsing that
happened deep inside getopt_long() somewhere.
In fact - this caused builds on MSVC to crash sometimes. The other thing
that caused MSVC to crash was if an flag that had an optional argument
was the last on on the command line (for example 'iio_info -a') we would
use a index that exceeded the actual memory allocations, so check for
that and don't do it.
Now, make sure to pass complete arguments to things, and fix the bounds
checking which seems to resolve all the issues on Linux and Windows.
Signed-off-by: …
=> iio_utils: rework/fix command line argument parsing

tests/iio_attr.c
After putting together some automated tests for iio_attr (which I will
check in later), fix some inconsistancies in iio_attr, which makes the
return codes return error on errors, and success on a success.
Split up reporting of buffers, to make it easier to find scan, input and
output buffers. Now you can see things like this:
rgetz@brain:~/github/libiio/build$ ./tests/iio_attr -a usb -i -o -s  -c
Using auto-detected IIO context at URI "usb:3.49.5"
IIO context has 5 devices:
iio:device0, adm1177: found 0 scan, 0 output, 2 input channels
iio:device1, ad9361-phy: found 0 scan, 5 output, 4 input channels
iio:device2, xadc: found 0 scan, 0 output, 10 input channels
iio:device3, cf-ad9361-dds-core-lpc: found 2 scan, 6 output, 0 input channels
iio:device4, cf-ad9361-lpc: found 2 scan, 0 output, …
=> iio_attr: after automaticed testing, make return codes consistant.

libiio.iss.cmakein
From the official documentation: "When this flag is used and the file
already exists on the user's system and it has the same version number
as the file being installed, Setup will compare the files and replace
the existing file if their contents differ.
The default behavior (i.e. when this flag isn't used) is to not replace
an existing file with the same version number."
=> libiio.iss.cmakein: Drop the "ignoreversion" flag and use the "replacesameversion" flag instead.

tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h
decrease the output of iio_attr.
To go back to "normal", use the new '-v' flag (verbose).
To quiet everything use the '-q', which is useful for checking error
codes.
tweak the context creation in iio_common for better error reporting
=> iio_attr: change verbosity of output

.travis.yml
This should fix a deploy stage issue on the travis-ci builds caused by an
invalid yaml config.
=> Fix tag requirement on pypi travis-ci

CI/travis/before_install_linux
This fix will remove "UserWarning: Unknown distribution option: 'long_description_content_type'"
=> Upgrade python setuptools for CI

iio.h
Which (as of today) is expected, but not documented.
=> iio.h: add some doc about iio_context_clone not working on usb

libiio.pc.cmakein
Alternative fix for: https://github.com/analogdevicesinc/libiio/pull/563
It is [not generally true](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files) that `CMAKE_INSTALL_<dir>` variables are relative paths. Absolute paths will cause things like this to appear:
includedir=${prefix}//nix/store/87zhscw1p08nqm73ls2sd82zmr1a8rni-libiio-0.21-dev/include
It would be best if the paths were relative to `${prefix}` pkg-config variable so that they could be [overridden](https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/) but since that is not easy to do in CMake, we will just use absolute paths.
libiio does not expect other project to install artefacts to its installation paths so non-overriddable paths should no do much harm.
=> cmake: Avoid path construction in pkg-config file

tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_stresstest.c, tests/iio_writedev.c
and add it to the utils that did not support it before.
Inspired-by:  Michael Hennerich's #565
=> tests: Support context timeout in common manner

bindings/python/README.md, bindings/python/doc/index.rst, bindings/python/setup.py.cmakein
The name libiio is not available in pypi since Fedora blocked out future
package names that share the same name as their yum/apt names.
Therefore, we switch to using the name pylibiio for pypi. This change
updates the doc and packaging script. v0.21 has already been uploaded
with this name to pypi.
=> Update python package name

mdns.h
This would help the cross compile process where these headers are not
found because their filenames are lowercase. This happens if the host
where the cross compiling is done is case sensitive when it comes to
file paths.
=> dnssd: Use lower case when including Windows headers

man/CMakeLists.txt, man/make_man.sh.in
as pointed out in #555, we assumed that iio.h was always one directory
up, which is sort of bad form.
Don't make that assumption, and process things with the CMAKE system.
=> man: allow man pages to be built when not in a ./build dir

CMakeLists.txt
=> cmake: set _WIN32_WINNT when compiling with mingw

bindings/python/setup.py.cmakein
This should fix #561
Signed-off-by: Julien Malik <julien.malik@paraiso.me>
=> python: Do not verify whether libiio is installed when cross-compiling

appveyor.yml
We can revert this commit once appveyor updates the installer for MSYS.
https://www.msys2.org/news/#2020-06-29-new-packagers
=> appveyor.yml: Update the MSYS build keyring manually.

tests/iio_attr.c
getopt doesn't understand the difference between the '-' before an
option and the '-' before a negative number. It can not - they are both
the same, and in some applications option zero (-0) might be valid.
in iio_attr this causes problems when we try to write negative numbers
root@analog:~# iio_attr -o -c adrv9002-phy voltage0 hardwaregain -10
iio_attr: invalid option -- '1'
Since the only time we do this in in iio_attr, handle the last option
differently (if the last option is a negative number).
This does mean we still don't pass -foo to an attribute to be written,
since iio_attr thinks that is an unknown "-f" option.
./tests/iio_attr -v -a usb -o -c ad9361-phy voltage0 hardwaregain -foo
Using auto-detected IIO context at URI "usb:3.39.5"
./tests/iio_attr: invalid option -- 'f'
but …
=> iio_attr: accept negative numbers as data to write to

tests/iio_common.c
Right now iio_reg and possibly other tools are broken.
Registers and values are typically provided in hex values.
strtoul() with base 10 returns error when hex values are parsed.
So iio_reg will always clear register 0 which in most cases will
reset the device.
=> tests/iio_common: Fix HEX value parsing in sanitize_clamp()

local.c
There's a bug, when enabling a buffer (with local_buffer_enabled_set(),
i.e. writing to 'buffer/enable'), we can get -EINVAL, because the scan_mask
is invalidated by the kernel.
The issue seems to be that the local_open() exit-on-failure path is
un-balanced. Some things don't seem to be cleaned-up on exit-on-failure.
This is seen with iiod trying to open a high-speed buffer device, where the
exit-on-failure path does not call munmap() on the buffers, nor does it
free the memory allocated for the buffer (in libiio). On the next
retry/open the buffer device is locked and -EBUSY is returned.
Essentially, this leaks resources (a file-descriptor and some memory for
the buffers).
Closing and re-opening iiod fixes the issue.
Also, the local_close() function should not exit on the first fail in …
=> local: harden local_close() and use it for local_open() failure

local.c
Patch 4b0a7a26182d86 ("local: handle error codes in local_close()") omitted
one return value read for close().
Coverity caught that. This patch reads the return value for
'close(pdata->cancel_fd);'
=> local: add omitted return value read from close() in local_close()

utilities.c
This patch fixes a wrong comparison leading to a false failure. We want to
return error if the env var size is bigger than max size and not the other
way around.
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
=> utilities: Fix getenv function

CMakeLists.txt
Building libiio with cmake 2.8.7(minimum version required) would fail due to cmake(2.8.7) not being able to copy a list of files separated by ";" to a destination. A solution to this problem is to create a list of commands containing a copy command for each iio test target file. With this approach the minimum required CMake version is not touched.
Tested with CMake version 2.8.7 and 3.18.2
Signed-off-by: DanielGuramulta <Daniel.Guramulta@analog.com>
=> CMake: fix build with cmake 2.8.7

local.c
Fix #357
If a target buffer is too small, right now, we try to put a partial fill
in the buffer, and return sucess (which is wrong).
Now we will return EFBIG, and leave the target buffer empty. This will
make the local backends the same as the otherbackends.
=> local.c: when target buffer is too small, fail

context.c, dns_sd.c, iio-private.h, iiod/ops.c, local.c, network.c, usb.c, xml.c
This PR is trying to reboot this PR https://github.com/analogdevicesinc/libiio/pull/9
Which is essentially a modularization of libiio to be able to add more backends in a more dynamic fashion.
The intent is to be able to add more backends (like GPIO, HWmon, and other stuff).
But to get there, ideally we'd need to make libiio a bit more modular, and first convert all current backends to be made modular (independent of internal structures like iio_context, iio_device, etc).
We don't need to split libiio.so in smaller libs [if we don't want to]; we can implement this option to allow libiio to be built as a single library or as a smaller set of libraries, one being libiio-core.so and the others being libiio-<backend>.so (which would be loaded by libiio-core.so).
But if adding more backends, …
=> iio: context: start hiding the iio_context object inside context.c

iiod-client.c, iiod-client.h, network.c, serial.c, usb.c
All the iiod-client (type) backends create a context lock and pass it to
the iio_client object via iiod_client_new().
This looks wonky, since the iio_client routines do a lot of things with
that lock.
The serial backend uses it quite extensively. The USB doesn't (explicitly
lock it at all), and the network backend only uses it during
network_close() (which may be un-required).
For the cases where this lock is still used, a iiod_client_mutex_{un}lock()
function pair is created to access the lock. We may find that we can hide
the lock entirely, but until then this change shouldn't change any current
behavior.
=> iiod-client: move context lock inside the iiod_client object

network.c, serial.c
For the network backend, the logic looks a bit spread across the network_create_context() function.
It looks like it would make sense to move it into it's own function.
The serial backend's description logic is pretty simple.
But moving these into separate functions does clean things a bit and and might give us the opportunity later to convert the
'iio_context->description' into a backend op [if it makes sense].
=> network,serial: split description creation into own functions

network.c
This was not happening on Travis-CI because it's compiling on Linux, and
HAVE_IPV6 is defined.
Under Windows/Appveyor it seems it isn't, so the 'err_free_description'
label in network_get_description() is unused.
This also seems to have happened, because Appveyor builds were failing.
=> network: move free(description) under #ifdef HAVE_IPV6

context.c, iio-private.h, local.c, network.c, serial.c, usb.c
This adds a iio_context_get_pdata() accessor to retrieve the private information of an IIO context object, to better hide it from IIO backends.
=> iio: add iio_context_get_pdata() accessor and use it

iio-backend.h, local.c, network.c, serial.c
This doesn't get rid of the 'ctx->description' object; that will still be
around and cache the description.
The get_description() splits the creation logic of the description into a
backend op. That way, we can think of splitting the creation of an IIO
context into an 'alloc()' and 'init()' part where:
* an IIO context is allocated first in libiio core
* it's backend init() routine is called
* it's backend get_description() routine is called
The idea of the 'get_description()' op is to return a pointer, that libiio
core will manage/free. Hence the return is 'char *' vs 'const char *'.
=> iio: backend: add get_description() backend op & hook it into backends

bindings/csharp/Context.cs
During context creation, the context attributes' name and value were not marshalled correctly from native to managed memory, creating a crash when the GC collected gen2 heap memory.
Signed-off-by: Lehuraux, Max <Max.Lehuraux@analog.com>
Co-Authored-By: cristi-iacob <52404495+cristi-iacob@users.noreply.github.com>
=> Fix marshalling in C# bindings

CI/travis/before_install_linux, CI/travis/lib.sh
To get the lsb_release command working some packages need to be
pre-installed.
The docker images come pretty bare, so they need to be installed before.
This can complicate things, because we need to make sure that all builds
down the pipeline install this package.
The utilities that wrap lsb_release can be re-implemented with simple shell
commands and parsing of /etc/os-release.
This change does that.
=> ci,travis: remove lsb package requirement

local.c
Resolves build problems when compiling with -Werror=shadow.
Signed-off-by: [Marc Sporcich] <marc@epiqsolutions.com>
=> #611:Eliminate variable shadowing in local.c

.travis.yml
This has mostly cleanup value. Since it's duplicated everywhere, it may
make sense to just move the EXTRA_SSH to a global place, and not duplicate
it anymore.
=> .travis.yml: unify EXTRA_SSH env var

appveyor.yml
Appveyor build failed because the RC compiler detection failed. 
This might be caused by the CMake package update (checked repo.msys2.org and the update was done 2 days ago, when the builds started failing). 
CMake does not detect an appropriate compiler for RC, so we point it to the right path.
=> Appveyor: Use mingw64/bin/windres as RC compiler for 64 bit.

.travis.yml
Xcode 12 has been out for a while now.
This change adds a build for it so that we can start putting it through the
pipeline.
=> .travis.yml: build & deploy for Xcode12

bindings/python/iio.py
The libiio python bindings currently have two bugs that I've come across, relating to triggers.
1. `<Trigger>.frequency` - throws an error, since it uses the `frequency` attribute instead of correct attribute name, `sampling_frequency`
2. `<Device>.trigger` - always returns `None`, even when the device has a trigger. This seems to be because the function is comparing two python `_Device` objects for equality, instead of comparing their values.
1. `frequency` is replaced by `sampling_frequency`, so that calling `<Trigger>.frequency` does not throw an error and instead returns the integer frequency of the trigger.
2. `<Device>.trigger` - has an updated function signature to reflect the c function's arguments (second argument should be a double pointer) and compares the `id` (which are …
=> Fix Python bindings bugs relating to Triggers

tests/iio_readdev.c, tests/iio_writedev.c
Currenly set at 64, it is not optimal when a smaller number of samples
are requested. For instance, if 4 samples are requested, we still have
to wait for up to 64 samples to come in to return.
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
=> tests: iio_readdev: Set minimal buffer size to 2

examples/dummy-iiostream.c, examples/iio-monitor.c, iiod/iiod.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_stresstest.c, tests/iio_writedev.c, usb.c, utilities.c
iio_error: Always print out the error code.
When debugging some Windows code, there were some weird strings coming out. 
This tweak will make it easier to find things, as we now follow the rule:
* always include the error number along with the message, as that's the unambiguous part
This does two things:   
* update iio_strerror to always append the error number, so coders can be more lazy.
* be lazy, and never print out error codes in the leaf code
=> add errcodes to all faults

CI/travis/before_install_linux, CI/travis/inside_docker.sh, CI/travis/lib.sh, CI/travis/make_darwin, CI/travis/make_linux, azure-pipelines.yml
Currently just does a build, an only on PRs to save time/resources.
Deployments will be re-added in the next commit series.
On push events only staging/* branches are built.
This is an opt-in mechanism, since we may not want to build everything,
which is a waste of resources.
Dropped CentOS 6 builds during migration; we can re-add it; but it's old
enough.
The supported MacOS X images are version 10.14, 10.15 and 11.0.
Suffixed builds with CPU architecture `_x86_64`. We may want to add `_arm`
or `_arm64` later.
=> ci,azure-pipelines: add initial yaml file

azure-pipelines.yml
Otherwise the string that shows up is just 'CmdLine'.
Since we've ported the old scripts, those had 3 stages (in Travis-CI):
1. Install dependencies
2. Run the Build
3. Deploy the artifacts
=> ci,azure-pipelines: add names for the steps in the job

azure-pipelines.yml
Matrix strategy adapted from Travis Collins' work on libiio with Azure Pipelines.
This reduces duplication of the same steps for Linux & Mac builds.
Publishing build artifacts for Mac & Linux.
Also adapted from Travis Collins' example. But this uses the
PublishPipelineArtifact@1 (some parts of the doc recommend this over
PublishBuildArtifact@1).
The artifacts will be published for non-Pull-Request cases.
And the artifact names have been parametrized based on branch, so that
'master' artifacts propagate to the next builds, and release artifacts
(20XX_RY branches) propagate over the same branch names.
=> ci,azure-pipelines: rework to matrix strategy and publish artifacts

azure-pipelines.yml
The name of the library (libiio) was added as a suffix to make it more
unique. But these is no collision possible, since we need to specify which
from pipeline to pull these artifacts from.
=> ci,azure-pipelines: simplify artifact names

iio-private.h
This limit was arbitrarily chosen. Prior in truncating the string,
it got parsed by libini, processed by xmlEncodeEntitiesReentrant().
So we know it is zero terminated and a valid string.
Keep a limit by increase it by 8x. Hopefully no valid use case will ever
exceed this limit.
This fixes a regression on M2k where the temperature calibration values
attribute exceeds 4k.
ERROR: Internal libIIO error: iio_context_create_xml str length issue
ERROR: Unable to create local context: Cannot allocate memory (12)
=> iio-private.h: Increase MAX_ATTR_VALUE

CI/build_win.ps1, CI/install_deps_win.ps1, azure-pipelines.yml
This change adds a minimal configuration to build some Windows artifacts
for libiio.
These are stored after the pipeline is done.
Adapted from Travis Collins' work.
Added into PowerShell scripts. Ideally we should not add any script-code
into yaml files, as that makes it harder to scale, and even harder to
migrate (if ever will be needed again).
Publishing artifacts, the generated DLL, static library, and the iio.h
header, which will be used in the next jobs.
=> ci,azure-pipelines: add windows builds

CI/travis/make_linux, azure-pipelines.yml
This time we add a CHECK_AGAINST_KERNEL_HEADER env var to enable this
script, and tie it to the Ubuntu 20.04 build. Since this is the most recent
Linux image.
=> ci: re-enable check-kernel script for linux

bindings/python/iio.py
The Device class was only holding a weakref of the Context object. This could lead to calling the Context's destructor before removing all its references.
An example of the crash can be found in #628.
Weakref was permitting Python to call the Context destructor even if it was referenced in the device object. Changing the weakref to a full reference should solve the issue.
=> Python bindings: Solved Python bindings Context destructor bug.

CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_linux, azure-pipelines.yml
These ARM builds should work also on Raspberry Pi (starting with Raspbian
Buster). These packages should install on newer (than Buster) Debian
versions as well.
Tested on a Raspbian that the libiio deb package installs and iio_info
runs, and iiod starts (even though is started manually, but this requires
some more work for packaging the service installation).
=> ci,azure-pipelines: add ARM{64} Debian Buster builds 

CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_linux
All Linux distros [except for Ubuntu 16.04] support Python 3.6 or newer.
For this version it might make sense to no longer build docs, since it's getting old (5 years in a few months).
With this change we switch to using the distribution's Python3 package.
This unclutters some Python setup.
Since we're moving to Azure, it is a good opportunity to do this cleanup.
=> [RFC] ci,linux: reduce python pip deps and use distro's python3

CI/travis/before_install_linux, CI/travis/make_linux, azure-pipelines.yml
Sadly, Azure Pipelines, seems to have their Ubuntu images pre-configured
with stuff we don't want.
The stuff that seems to pain us more is that they install some PPAs that we
don't need, and that results in installing newer versions of packages than
what Ubuntu officially supports.
Example (for libxml2):
https://dev.azure.com/AnalogDevices/OpenSource/_build/results?buildId=301&view=logs&j=619eeb56-1e32-5748-8918-b91b4093a911&t=abb0dc85-7ed9-5413-b9ef-6502ddb91e27
```
The following packages will be upgraded:
libxml2 libxml2-dev
```
```
Get:13 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libxml2-dev amd64 2.9.10+dfsg-5+ubuntu16.04.1+deb.sury.org+3 [809 kB]
```
When trying to test these deb packages on an official Ubuntu docker, it
complains that it requires a newer libxml2 …
=> ci,azure-pipelines: wrap all Ubuntu builds in official docker images

CI/install_deps_win.ps1, azure-pipelines.yml
Microsoft has a pretty good track record for making their Visual Studio
compilers work fine across multiple Windows versions.
And libiio isn't a super-complicated project, in terms of scale and what
Visual Studio can handle.
So, instead of building on 2 versions of Visual Studio, might as well build
for a single one, but for different architectures.
Building for Win32 & Win64 is more important.
This change re-purposes the VS2017 build to VS2019_Win32 (i.e. Visual
Studio 2019 and Win32).
=> ci,azure-pipelines: re-purpose VS2017 builds as VS2019_Win32

CI/travis/lib.sh
Some env-vars can have spaces. To prevent issues with these, we need to
add explicit double quotes when saving them in the file that the docker
image will read.
=> ci,lib.sh: double quote the env-vars passed to docker

serial.c
The descrpition of sp_blocking_read_next() specifies that 0 is returned on timeout. This commit handles this.
An issue has been observed when trying to create a context for the wrong serial port (where no tiny-iiod exists on the other end) which causes a really long wait time because sp_blocking_read_next() was being called for at least 1024 times and each time it timedout after 1 second.
This fixes https://github.com/analogdevicesinc/iio-oscilloscope/issues/280
=> serial: Detect timeout when reading a byte from serial port

channel.c, context.c, device.c, iio-private.h, local.c, xml.c
The entire XML generation (the one done manually) is pretty difficult to
change, so if someone wants to add some attributes (because some kernel ABI
got updated), it's easy to change and introduce leaks.
This code as-is already has some potential leaks (and faults).
One example is in in iio_device_get_xml() (on the error path), where:
```
err_free_debug_attrs:
while (k--)
free(debug_attrs[k]);
free(debug_attrs);
err_free_debug_attrs_len:
free(debug_attrs_len);
err_free_buffer_attrs:
while (k--)
free(buffer_attrs[k]);
free(buffer_attrs);
```
Now, it's obvious that such errors can be fixed, but a better idea is to do
a single allocation and use the 'snprintf(NULL, 0, ...)' to count the
amount of memory we need for the XML string.
This change does that. And all the allocations (that were …
=> iio: rework entire xml generation

examples/CMakeLists.txt
Running cmake for the examples warns:
-- Curses Development Kit (CDK) missing or too old, skipping iio-monitor
This happens because PTHREAD_LIBRARIES is not set.
Fix that by looking for the phtread library first.
After that it fails with:
Unknown CMake command "check_symbol_exists".
Fix that by including CheckSymbolExists.
Fixes: 88b946f4b897ea18 ("iio-monitor: Now the c90 warnings are gone, fix real warnings")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
---
On Ubuntu 20.04.2 LTS.
=> examples/cmake: Fix iio-monitor dependency checks

iio-private.h, xml.c
This function is not used anywhere anymore since commit 9d79757.
Fixes #588.
=> xml: Remove unused function encode_xml_ndup()

CMakeLists.txt, iio.h
Set the LIBIIO_STATIC define when compiling a static library, which then
causes the __api to be resolved as empty.
This fixes building statically under MSVC.
Fixes #616.
=> CMake: Allow building as static lib in MSVC

tests/iio_common.c
When using iio_readdev, stdout is reserved for the data output; so
information messages about the context creation must be sent to stderr
so that the data stream is not polluted.
Fixes #583.
=> tests: Print context creation messages to stderr

CMakeLists.txt, iio-config.h.cmakein, iiod-client.c, iiod/CMakeLists.txt, iiod/iiod.c, iiod/lexer.l, iiod/ops.c, iiod/ops.h, iiod/parser.y, iiod/usbd.c
When compiled WITH_ZSTD, the ZPRINT command will return the same XML
string the PRINT command returns, but compressed with the ZSTD
algorithm.
The XML string is compressed when IIOD starts, and as such, once started
this has zero overhead.
Then, the ZSTD-compressed payload that can be decompressed into
the original XML string of the remote context. If the remote IIOD does not
support ZPRINT, it will simply revert to using PRINT instead.
This can dramatically speed up context creation when using a slow
transport (e.g. serial), as the XML strings can be really big.
For instance, the XML string of the ADALM-Pluto is close to 25 KiB.
On a standard 57600 bps UART connection, this would take about ~3.4
seconds to transfer. The compressed payload amounts to only about
3.7 KiB, which would take …
=> Add support for ZSTD-compressed metadata

context.c, iio-private.h, iiod/dns-sd.c, iiod/iiod.c, iiod/ops.c, iiod/usbd.c, utilities.c
This set of commits work on sanitizing the context attributes, so that they can be used in XML.
I did move `iio_snprintf` to being its own function. See the corresponding commit for details. `vsnprintf` is listed as supported in Microsoft's docs, so I expect it to build under MSVC with no problems.
=> Sanitize context attributes for XML

iio-private.h
Use the 'printf' format on all GNU compilers, which includes the
MinGW-flavoured GCC and Clang (which is not GNU, but says it is).
=> Fix warnings under MinGW and Clang

iiod-client.c, iiod-client.h, network-unix.c, network-windows.c, network.c, network.h, serial.c, usb.c
Instead of having the iiod-client API use a void* pointer to represent
the client platform data, use a pointer to a 'struct iiod_client_pdata',
that can be defined differently in each client.
This makes the code more robust as the compiler will properly enforce
type safety.
=> iiod-client: Pass client data as pointer to struct iiod_client_pdata

iio-private.h
We don't actually *need* any of the GNU printf format specifiers.
However, older versions of MinGW will complain about C99-compliant
specifiers like %lld unless 'gnu_printf' is used.
Since this is used only with GCC, which is the "GNU C Compiler", it is
pretty safe to enable the 'gnu_printf' format unconditionally.
=> Use gnu_printf format with GCC

CMakeLists.txt, network-unix.c, network.c
I broke things by removing unconditionally `_GNU_SOURCE` in a previous commit, the `WITH_NETWORK_GET_BUFFER` option does need it.
Note that this option is OFF by default which explains why nobody noticed.
=> Various CMake/Network fixes

iio-private.h, iiod/ops.c, iiod/ops.h, iiod/usbd.c
With this patchset, IIOD does not depend anymore on any of the private functions and structures of libiio, and only accesses everything through the public API.
One "functionality" of IIOD has been dropped in the process: the support for IIO devices that are both input and output. I think this case never happened and will never happen, so it should be OK.
=> IIOD: Drop dependency on private headers

iiod/ops.h
This header used to get pulled in via iio-private.h which was removed in commit
3c36a0cc7da78ef01d1bef3bd501952b71f85962.
Signed-off-by: Edward Kigwana <ekigwana@gmail.com>
=> IIOD: Fix building with AIO

CI/travis/make_linux, CMakeLists.txt
https://ci.appveyor.com/project/analogdevicesinc/scopy/builds/39249068/job/yh1k2u4t425vsxp5
We got this error when building libiio. We could of course set cmake with -DWITH_SERIAL_BACKEND=OFF and it would work. However in my opinion the serial backend should not be enabled by default, but rather be specifically-enabled by the user (the user will know he wants to use the serial backend)
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> CMakeLists.txt: Disable WITH_SERIAL_BACKEND by default

dns_sd.c, network-windows.c
Because of the missing headers, build failed when compiling on Ubuntu1804
image supported by Appveyor, with MinGW compiler.
=> network: Include headers for the errors that are used

dns_sd.c, iio-private.h, local.c, scan.c, usb.c
A small set of changes that I made for an upcoming pull request to the dev branch, that I thought could be merged into master instead.
This PR removes the "scan context" structures as they are not really useful, and reworks and simplifies iio_scan_result_add().
=> Context scan cleanups

azure-pipelines.yml
This Azure Pipeline was divided into two stages:
- first stage is for builds
- second stage runs at the end of the first stage for download and push the artifacts into SW Downloads in the 'azure_builds' directory
Artifacts are overwritten in SW Downloads only when Azure Pipeline is running for the master branch.
=> Push artifacts to SW Downloads

iio.h
The behaviour of the function changed about one year ago in
commit 2e400fae ("getenv : keep Windows happy by using _dupenv_s rather
than getenv") without anybody noticing; so fix the documentation so that
it describes better the current behaviour.
=> iio.h: Fix documentation of iio_create_default_context()

iio-debug.h
Two small fixes to the IIO debug functions in the dev branch:
- the default log level, set at compilation time, was ignored when the params pointer was NULL;
- the error code was printed twice in the *_perror macros.
=> Fixes for IIO debug functions

CMakeLists.txt, bindings/csharp/CMakeLists.txt, bindings/python/CMakeLists.txt, cmake/Install.cmake
Fix the Python bindings not being properly installed, and bump the CMake script of the bindings to 3.10 to match the main script.
=> CMake: Fix Python bindings documentation not properly installed

local.c
Fix the error message **"ERROR: Error during buffer disable: Success"**
Which is actually a combination of two bugs:
- `local_close()` called `local_buffer_enabled_set()`, and read the error code from `errno` if the return value was non-zero, while this function returned the error code directly;
- `local_buffer_enabled_set()` returned positive values on success, which means that checking for a non-zero return value is invalid.
=> Local backend: Fix invalid error message in local_close()

network.c
If we have `#define HAVE_DNS_SD 0`, Clang 9 (and probably other versions)
will correctly detect that `if (HAVE_DNS_SD && ret)` is dead code,
but will fail to detect that `if (ret && HAVE_DNS_SD)` is dead code.
If the dead code calls symbols not provided at link time, then linking
will then fail.
Fix this by swapping the two expressions in the "if" block.
Stupid, right?
Reported-by: Adrian Suciu <adrian.suciu@analog.com>
=> network: Fix build under Clang

bindings/python/iio.py, compat.c, examples/iio-monitor.c, iio-compat.h, iio-private.h, iio.h, scan.c, tests/iio_common.c, usb.c, utilities.c
This PR introduces a new API for scanning for IIO contexts in Libiio 1.x.
The old API has three data types and 10 API functions, which is too complicated for many people, me included. The new API has only one data type and 5 API functions.
The old API is moved to the compatibility library so that old applications will still work. It is now implemented on top of the new API.
=> New scan api

context.c, dns_sd.c, dns_sd.h, dynamic-unix.c, dynamic-windows.c, dynamic.c, iio-backend.h, iio-config.h.cmakein, iio-private.h, local.c, network.c, scan.c, usb.c
This PR adds a mechanism to support scanning IIO contexts in built-in and module backends. This will later allow the network and USB backends to be compiled as modules.
It adds a `.scan` callback to the iio_backend structure, which will now be called by the core when scanning for the backends' available IIO contexts. It also updates the dynamic.c file to support scanning, by browsing the libiio modules directory, opening each module and calling its .scan function if the module's URI matches one of the requested backends.
=> Enable scan support in module backends

context.c, iio-private.h, local.c, xml.c
Some simple fixes to the local context, mainly to avoid error codes being lost.
I also renamed the PTR_TO_ERR / ERR_TO_PTR macros to just PTR_ERR / ERR_PTR since people are more familiar with them, and the error code is now just "int" instead of "intptr_t" which prevents warnings about implicit casts to a type of a different size.
=> Local context fixes

examples/CMakeLists.txt, examples/adrv9002-iiostream.c
This is analogous to adrv9009-iiostream. Just serves as an example on how
to stream data on adrv9002 using libiio.
Signed-off-by: Nuno Sá <nuno.sa@analog.com>
=> examples: add example for adrv9002

context.c
Looks like the previous code hasn't been tested...
This fixes the generation of the XML representation of the context when
context attributes are present.
It additionally removes whitespace characters in two blank lines.
=> Fix XML generation with context attributes

libiio.rules.cmakein
Having "iio_info -s" in the udev rule will scan all available backends,
and some (like the network backend) may take a while to process.
Run "iio_info -S usb" instead to specify that we only want to scan USB
contexts.
@AlexandraTrifan can I add you as Reported-By?
=> Update udev rule to only scan USB

context.c, iio-backend.h, iio-private.h, iiod-client.c, iiod-client.h, network.c, serial.c, usb.c, xml.c
Hi,
Since the library version on the remote side is not expected to change during a iio_context's life, it is static data and therefore should be passed as part of the XML string.
This PR makes it easier for me to introduce other changes (less code to update to the new APIs and protocols).
It has two notable implications:
- As usual when the XML string is updated, the version of the remote libiio must be equal or newer to the version of the PC (the inverse is not true).
- IIRC, iio-osc (or was it Scopy?) uses a thread that calls iio_context_get_version() in a loop with the sole purpose to detect broken communication. That won't work anymore. I think one safe replacement would be to use iio_device_get_trigger(), since this is guaranteed to be a call to IIOD.
Cheers,
-Paul
=> Put library version in XML string

CI/travis/before_install_linux
For CentOS 8: 
-CMake has a bug when installed from repos. Must grab from kitware
-doxygen must be installed with "dnf", not "yum"
=> Fix cent os builds

bindings/python/iio.py
When multiple devices with the same name exist, label is used to
differentiate them. Update find_device to also support labels.
Actually not sure, why we're not calling the C API with that...
=> bindings: python iio.py: find_device() also use label

CMakeLists.txt
Even if NO_THREADS is set to ON, we do want to compile lock.c inside the
library, since it will provide the symbols, just with dummy
implementations.
=> CMake: Fix build with NO_THREADS=ON

usb.c
The jump to the cleanup epilog pointed to the wrong label, which caused
the libusb context to never be freed on error.
=> usb: Fix goto to wrong label

iiod/ops.c, iiod/parser.y, network.c
In an effort to simplify the current iiod/client protocol, so that the new async protocol will be easier to implement, remove the EXIT command of IIOD, which was sent by the client right before sockets were closed, and instead exit IIOD's client thread when the sockets are actually detected as closed.
=> IIOD: Remove EXIT command

CMakeLists.txt, tests/CMakeLists.txt
Android does not use discrete pthread library but it is
contained in the standard C library https://developer.android.com/ndk/guides/stable_apis#c_library
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> CMakelists.txt: add support for Android

bindings/csharp/Context.cs, bindings/python/iio.py, compat.c, context.c, examples/dummy-iiostream.c, iio-compat.h, iio.h, tests/iio_info.c, utilities.c
This set of commits adds thee new functions `iio_context_get_version_major`, `iio_context_get_version_minor`, `iio_context_get_version_tag`, convert the examples / tests / bindings to this new API, and moves the old `iio_library_get_version` and `iio_context_get_version` functions to the compat library.
These two had a few major problems:
- They returned the values in their parameters; therefore, calling code
had to define local variables, then call the function, then use these
local variables in e.g. a printf() call. The new API is simpler, as
the values are returned directly by each function.
- The "git_tag" parameter was defined in iio.h as an array of 8
characters (7 ASCII characters + \0 byte). While it may not happen
anytime soon, it is doomed to fail as soon as the number of …
=> New context / library get_version API

context.c, iio-backend.h, iiod-client.c, iiod-client.h, network.c, serial.c, usb.c
This reverts commit 48e5852ac1b42f56727ee01a7cc0d2d76775bc13.
If we remove the .get_version() callbacks, then in case we're running
with an old version of IIOD, libiio won't have any way to read the
remote version.
=> Revert "backends: Remove .get_version() callbacks"

xml.c
Silence the warnings that used to appear when the XML backend
encountered XML tags it didn't know about. As long as the DTD verifies
the XML, we can assume that the XML is sane and unknown XML tags are
just tags that were added by newer versions of IIOD.
=> xml: Silence warnings with unknown XML tags

CI/travis/archive_artifacts.sh, azure-pipelines.yml
Each new version tag will trigger "PushToGithubRelease" job to run on Azure Pipelines. The result of this job is a draft release on Github.
Draft release will contain:
- buildartifacts
- changelog
- release title.
CI/travis/archive_artifacts.sh script was added in order to archive buildartifacts that will be pushed as assets in draft release.
=> Release process automatization

bindings/csharp/Device.cs
MSVC would fail with the following error:
error CS0106: The modifier 'readonly' is not valid for this item
Reported-by: Raluca Chis <raluca.chis@analog.com>
=> C#: public fields with getters/setters cannot be marked readonly

local.c
Previously, the detection of buffer-capable channels would fail when the
channel had attributes outside the scan_elements/ folder, as the channel
would be correctly marked as buffer-capable when the first attribute
was found, but then overriden as non-buffer-capable as soon as an
attribute outside the scan_elements/ folder was found.
It went unnoticed until now, most likely because there is generally
either scan-elements attributes or non-scan-elements attributes, and
rarely both.
Fixes #740.
=> local: Fix detection of scan-element channels

azure-pipelines.yml
For Windows builds, setup.exe file is generated for each modification on master.
With this modification, setup.exe file will be saved on SWDownloads with the other artifacts.
=> CI: push windows setup.exe to SWDownloads

bindings/csharp/Channel.cs
Provide a "format" field in the Channel object, which contains a
read-only DataFormat structure similar to iio_data_format.
=> C#: Add support for data format

azure-pipelines.yml
In this pull request:
- macOS-10.14 is removed because is deprecated from Microsoft-hosted agents in Azure Pipelines
- macOS-11 is added to build
=> CI: update macOS version

iio.h
Add the missing enums from <linux/iio/types.h> and protect all of them
from double-definition by wrapping them with the header's protect
guards.
Fixes #758.
=> iio.h: Protect against inclusion of <linux/iio/types.h>

tests/iio_common.c, tests/iio_common.h, tests/iio_readdev.c, tests/iio_writedev.c
Add a new --benchmark (or -B) option.
With this option enabled, no data is written to the standard output (for
iio_readdev) or read from the standard input (for iio_writedev).
Instead, the buffers are flipped as fast as possible. This functionality
permits to benchmark the speed at which the data flows, and compare the
performance of the various backends and/or with various buffer sizes.
=> iio_{readdev,writedev}: Add benchmark feature

iiod/init/iiod.service.cmakein
This patch adds support to source iiod options via /etc/default/iiod
=> iiod/init/iiod.service.cmakein: Add support for extra iiod options

iiod/init/iiod.service.cmakein
IIOD does not handle the hardware changing (in /dev or /sys) after it
has been started. Therefore, we must ensure that all modules have been
loaded before IIOD starts.
Note that this is explicitely marked as a bad practice in systemd docs,
which recommends the service to handle udev events instead. Since IIOD
and libiio don't support hardware hotplug we don't really have a choice
right now, but this workaround should be dropped as soon as hotplug
support has been added.
=> iiod: systemd: Add dependency on systemd-udev-settle.service

bindings/csharp/Device.cs, bindings/python/iio.py, channel.c, iio-private.h, iio.h, local.c
These read-only properties will be True if the iio.Device is a hardware monitoring device, and False if it is a IIO device.
=> Add iio_device_is_hwmon() and iio.Device.hwmon property in bindings

tests/iio_readdev.c, tests/iio_writedev.c
Fix the --benchmark / -B feature that was added previously in iio_readdev and iio_writedev, and decouple the refresh rate from the buffer size and sample rate.
=> iio_readdev/iio_writedev: Fix benchmark feature

local.c
iio_device_get_sample_size_mask(dev, dev->mask, dev->words)
is the exact same as:
iio_device_get_sample_size(dev)
=> local: Simplify code

local.c
Add support for setting the watermark value, if the driver supports it.
The watermark value represents the number of samples that will be read
in one burst from the hardware. Since we read data at the granularity of
iio_buffer blocks, it makes sense to use the highest watermark value up
to the buffer's size. If the value is too high, the driver will
automatically adjust it to the maximum watermark value possible.
Fixes #780.
=> local: Add support for setting watermark

channel.c
Libiio being compiled without support for hwmon devices means that the
local backend won't try to probe hwmon devices; but hwmon devices found
by a remote libiio should still be usable across the network or USB,
even if WITH_HWMON is disabled locally.
Until now if the host libiio was compiled without hwmon support, it
could see the target's hwmon devices but their type was wrong.
Reported-by: Adrian Suciu <adrian.suciu@analog.com>
=> Fix hwmon channel type set to unknown if !WITH_HWMON

local.c
The watermark attribute may be set to read-only by the kernel. In that
case, trying to open it for writing will return -EACCES, aka.
"permission denied".
Therefore, the -EACCES error needs to be ignored. This is a bit
annoying, since we cannot know if it happens because the attribute
itself was set read-only by the kernel, or because the user simply
doesn't have the necesary access rights to write the file. But it is
rather safe to assume it is not the latter, as the "buffer/length"
attribute was written just a bit before without returning an error.
=> local: ignore "permission denied" error on accessing watermark

azure-pipelines.yml
This is a temporary solution until the new update of the CI.
=> CI: drop centOS 8 build

iio-backend.h, local.c, network.c, serial.c
This callback was introduced in commit d61f6296 ("iio: backend: add
get_description() backend op") but was never called anywhere, as the
backend's description string is also present in the XML directly.
=> iio-backend: Remove unused callback .get_description

man/iio_info.1.in, tests/iio_info.c
iio_info had two possible options to scan for contexts: -S (aka. --scan)
and -s, which did more or less the same thing, but -s didn't take an
argument and scanned all possible contexts.
Remove the -s option in the help text to reduce the confusion, while
still handling it for backwards-compatibility.
=> iio_info: Remove -s option

CMakeLists.txt, iio-config.h.cmakein, iio-private.h, iio.h, libiio.rules.cmakein, man/iio_attr.1.in, man/iio_info.1.in, man/iio_readdev.1.in, man/iio_writedev.1.in, scan.c, sort.c, sort.h, tests/iio_adi_xflow_check.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c, usb.c, utilities.c
A rewrite of #764.
This PR does a few things.
* Change the separator in the backends scan string from a colon to a comma (colon still supported for backwards-compatibility)
* Rework scanning to support having backends listed multiple times in the list
* Add support for specifying backend params, currently only for the USB backend: e.g. `usb=0456:b672`
* Update the libiio udev rule to only scan for the detected USB device
* Unify tools on the `--scan` (aka `-S`) option and updated the documentation and man pages
* Print usage examples on iio_readdev / iio_writedev.
The possibility to specify a USB device's VID/PID on the backends scan string makes it possible to only target a specific device, instead of probing all devices on the USB bus. This is useful for applications built around …
=> Support specifying VID/PID for scanning + steamline scanning in tools

README_BUILD.md
Add the list of missing features/and note about MSVC.
=> README_BUILD.md : update

bindings/csharp/Context.cs
Recent versions of the C# compiler would complain about the way the
iio.Version() constructors were implemented.
Rewrite them to fix these build errors.
=> bindings: csharp: Fix iio.Version()

context.c, usb.c
A couple of fixes that address warnings (treated as errors) under MSVC.
=> Fixes for building under MSVC

azure-pipelines.yml
Setup.exe file will be generated during Build stage so can be tested before merging a PR.
Artifacts will be published for PR's builds too.
=> CI: generate setup.exe in 'Build' stage and publish artifacts for PRs

CMakeLists.txt, buffer.c, channel.c, context.c, device.c, iio-backend.h, iio-private.h, iio.h, iiod-client.c, iiod-client.h, iiod/ops.c, local.c, mask.c, network.c, serial.c, tests/iio_readdev.c, tests/iio_writedev.c, usb.c, xml.c
This PR changes how the channels mask are handled internally.
It also modifies the `iio_device_get_sample_size` API function to take an optional channel mask as argument, and exports a new API function `iio_device_get_channels_mask`.
This is in preparation of the new blocks API, where each block has its own channel mask.
=> Update channels mask handling

tests/iio_common.c, tests/iio_common.h, tests/iio_readdev.c, tests/iio_writedev.c
Two small commits:
1. Fix a bug that Paul found that I introduced. in iio_read|write_dev - which was an oversight in a previous commit. allow multiple channels to be added on the command line.
2. In the past, you could put gibberish channel names, and read|write_dev would accept them (ignoring them). This sometimes lead to typos causing issues with "wrong" or "incorrect" data. Fix this by checking for a match, and errorring if there is something provided that doesn't match.
=> read|write_dev : fix bug & qualify channel names and err if bad name

iiod/serial.c
In the function start_serial_daemon, the "dev" variable was never freed
if the thread couldn't be created.
=> iiod: iiod-serial: Fix memory leak

channel.c, device.c, iio.h, local.c
Remove `iio_{device,channel,device_debug,device_buffer}_attr_{read,write}_all` functions for a big code cleanup, and because they are getting in the way of the new binary async. protocol implementation.
These functions may be re-implemented later in a much simpler manner.
=> Remove support for bulk read/write of attributes

channel.c, device.c, examples/ad9361-iiostream.c, examples/iio-monitor.c, iio-backend.h, iio.h, iiod-client.c, iiod-client.h, iiod/ops.c, local.c, network.c, serial.c, tests/iio_attr.c, tests/iio_info.c, usb.c
This PR reworks the attribute read/write functions.
It switches libiio to C11, and rename some functions so that `iio_device_attr_read()` and `iio_device_attr_write()` can be redefined as generic macros, which will accept multiple types.
It also adds a buffer ID argument to the buffer attribute read/write functions, in preparation of the multi-buffer support.
=> Update attribute read/write functions

dns_sd.c
The "port" is a uint16_t, not a int. The wrong format caused a
compilation issue on OSX.
=> dns_sd: Fix wrong type used for "port"

tests/iio_readdev.c, tests/iio_writedev.c
Register the signal handlers before everything else. Otherwise, the
signals might be sent to any thread that might be created by libiio, or
its dependencies, making these programs only killable by a signal 9.
=> tests/iio{read,write}dev: Fix unkillable process

local.c
If the INI file is present but cannot be read, print a warning about it,
but keep on creating the IIO context.
=> local: Ignore ill-formed INI files

utilities.c
When debugging some weirdness between the windows code and linux code
running mds, I noticed that iio_strndup() was behaving differently. :(
That is because the local implmentation for Windows was wrong.
Checking against:
https://github.com/gcc-mirror/gcc/blob/master/libiberty/strndup.c
(Which we can't use directly since it is GPL3, and not compatible with
LGPL), and checking against (which is BSD):
https://opensource.apple.com/source/Libc/Libc-1158.30.7/string/FreeBSD/strndup.c.auto.html
we can see the strlen we should be using is n, not n+1, which is what it
was before. :(
So, fix it.
=> iio_strndup : fix off by one error

tests/iio_common.c
MinGW 32-bit does not have timespec_get(). Strangely, the 64-bit version
does have it. But both have clock_gettime(), so only use timespec_get()
when building under Visual Studio.
Fixes #830.
=> tests: Fix build under MinGW

dns_sd.c, dns_sd.h, dns_sd_bonjour.c, network-windows.c, network.c, utilities.c
As defined in nbase.h (or in some system header file on Linux),
MAXHOSTNAMELEN is 64. This is the maximum length of a hostname,
but not of a DNS name, which may be longer. RFC 1035 spells out
that DNS names are formed of labels, each of which must be 63
bytes or less, and that labels are combined to form a DNS name
(a.k.a. FQDN) which may not exceed 255 bytes.
So add and use that, which fixed a long name issue for me.
=> Use FQDN_LEN instead of MAXHOSTNAMELEN for DNS names

network-unix.c, network.c
The Windows specific code has the cancellation functionality and the
ability to poll for data implemented, so it can use the non-blocking
mode as well.
=> network: Set non-blocking mode on Windows too

dns_sd.c
sometimes we get:
2: 127.0.0.1 on Raspberry Pi 4 Model B Rev 1.5 [ip:phaser.local]
3: 192.168.1.105 on Raspberry Pi 4 Model B Rev 1.5 [ip:phaser.local]
4: 192.168.2.10 on Raspberry Pi 4 Model B Rev 1.5 [ip:phaser.local]
5: 2601:190:400:da:a448:8c38:150a:7d4e on Raspberry Pi 4 Model B Rev 1.5 [ip:phaser.local]
obviously, 127.0.0.1 is not useful at all, so throw it away when we are looking for duplicates.
=> scan: ignore localhosts in scans

cmake/LinuxPackaging.cmake
The created .deb will search for the packages in this list when installed. The old packages don't exist and the install process ends up with an error:
`The following packages have unmet dependencies:`
` libiio : Depends: libaio (>= 0.3.109) but it is not installable`
`Depends: libavahi-client (>= 0.6.31) but it is not installable`
`  Depends: libavahi-common (>= 0.6.31) but it is not installable`
Signed-off-by: AlexandraTrifan <Alexandra.Trifan@analog.com>
=> cmake/LinuxPackaging.cmake: Fix apt dependencies list otherwise .deb is not installable.

include/iio/iio-debug.h
We don't need/want to set the errno variable anymore. Besides, the
header does not include <errno.h>.
=> iio-debug.h: Don't set errno variable

examples/ad9361-iiostream.c, examples/ad9371-iiostream.c, examples/adrv9009-iiostream.c, examples/dummy-iiostream.c, examples/iio-monitor.c, tests/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
Use SPDX license identifiers instead of a wall of text in each source file.
=> examples/tests: Use SPDX license identifiers

CMakeLists.txt
Use pkg-config to retrieve libusb dependencies such as `-latomic` and avoid the following static build failure:
```
/home/autobuild/autobuild/instance-4/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: /home/autobuild/autobuild/instance-4/output-1/host/arc-buildroot-linux-uclibc/sysroot/lib/libusb-1.0.a(core.o): in function `libusb_ref_device':
core.c:(.text+0x107e): undefined reference to `__atomic_fetch_add_4'
```
Fixes:
- http://autobuild.buildroot.org/results/3f421d6dfb48371f3fbc33fb25d23ad8f12a01d9
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> CMakeLists.txt: fix static build with libusb and -latomic

bindings/python/iio.py
The convert method from the Channel class had no functionality and the
read method performs the desired operation without requiring external
loops. Removing the method and dependent ctype definitions.
=> Remove python bindings to convert method

CMakeLists.txt
When libusb-1.0 is detected using pkg-config, we should include the
library's directory to the link path.
Since target_link_directories() is not available in the minimum version
of CMake that we support, override LIBUSB_LIBRARIES with the full path
to the library, to ensure that it will build fine even if the library is
installed at a non-standard path.
=> CMake: When using pkg-config, link libusb using its full path

azure-pipelines.yml
- remove cmake installation on macOS builds because is already installed on Azure VMs
- add `set -e` in scripts to fail if any errors exists
- remove installation of packages that are not found for ARM builds
=> CI: update Azure builds

dns_sd_windows.c
This syncs the application side with the updates in the mdns.h file
from: https://github.com/mjansson/mdns/
and does things according to the specs. (build up info from both A, AAAA and
SRV records), not just assuming that the DNS server is the host.
=> mdns: Fix/Update Windows mdns code

CI/azure/ci-ubuntu.sh, azure-pipelines.yml
This coincides with an upstream fix from https://github.com/sdgtt/Dockerfiles/pull/13 which uses the updated buildx API. My guess is that when the default image from Azure switched from 18.04 to 20.04, and as a result the version of docker changed, this broke the ARM builds.
This change updates the Azure pipeline to include the new required --platform argument
=> Update ARM builds to use --platform flag

azure-pipelines.yml
The main page of the documentation points to the man pages, so these
must be generated too.
=> ci: Build man pages as part of documentation

azure-pipelines.yml, context.c, iio-private.h, iiod-client.c, include/iio/iio-backend.h, include/iio/iio.h, tests/iio_genxml.c, xml.c
- Add support for creating a XML from a XML string embedded into a URI
- This means that every possible IIO context can now be created with the single function `iio_create_context`.
- The public function `iio_create_xml_context_mem` is now removed.
- The IIOD client code will now build a URI using the received XML string, and create a IIO context the standard way.
=> Rework XML context creation

man/make_man.sh.in
make_man needs the right path to iio.h
Signed-off-by: A. Maitland Bottoms <bottoms@debian.org>
=> fix make man

context.c, include/iio/iio-backend.h, include/iio/iio.h, local.c, network.c, xml.c
Cloning a context is a trivial operation with the new API. It is enough
to retrieve the context's params with `iio_context_get_params` and the
context's URI with `iio_context_find_attr(ctx, "uri")`, and call
`iio_context_create` with these.
=> Remove iio_context_clone()

block.c, buffer.c, context.c, dynamic-unix.c, dynamic-windows.c, dynamic.c, dynamic.h, iiod-client.c, iiod-responder.c, iiod/responder.c, include/iio/iio.h, include/iio/iiod-client.h, network.c, usb.c
Some fixes for the new libiio / IIOD async. interface.
- Fix IIOD sometimes answering a -ETIMEDOUT (-110) error, as the iiod_responder code did not handle infinite timeouts properly;
- Fix deadlock on client side occurring when the context creation failed (e.g. when IIOD returns a timeout...);
- Fix IIOD not understanding "write attribute" commands;
- Fix iiod-client sending invalid commands when trying to access an attribute that does not exist;
- Fix the network backend not destroying the iiod-client properly.
- Fix the dynamic loading code which was completely broken (wrong include paths on Linux, undefined variable on Windows)
- Fix prototype of iio_buffer_get_channels_mask()
- Remove carriage returns at the end of strings used in prm_perror
- Fix iio_block_destroy() blocking until …
=> libiio / iiod async interface fixes

iiod/responder.c
There was a copy paste error, all the opcodes were xxx_READ_xxx,
but they had to be xxx_WRITE_xxx.
Fixes: #890
Signed-off-by: Benjamin Menküc <benjamin@menkuec.de>
=> iiod: Fix writing of attributes

CI/azure/check_kernel.sh, azure-pipelines.yml
Add kernel check. It checks that the structures defined in iio.h are up-to-date with the one defined in the kernel's user-space API headers.
Script will run for each PR, inside Linux-Ubuntu-22.04 job.
Fixes: #891
=> CI:add kernel check

network.c, usb.c
Address a few problems with the USB and network backends in the dev branch:
- The USB backend simply wouldn't talk to IIOD, because the USB pipes were used by the iiod-client code before being initialized;
- The context creation functions of both the network and USB backends did set errno and returned NULL while everything else expected a pointer-encoded error code to be returned.
=> Context creation fixes

block.c, iiod-client.c, local-dmabuf.c, local-mmap.c, local.h, stream.c
Dequeueing an already dequeued block is not an error, but a no-op.
Return 0 instead of -EBADF.
Fixes: #901.
=> iiod-client: Dequeueing an already dequeued block is not an error

iiod/ops.c, iiod/ops.h, local-mmap.c
When using the new async. protocol, IIOD must be able to receive and
send at the same time. This was previously not possible when using AIO.
It didn't seem to matter with the network code, but it did matter with
the USB code.
To address this issue, use two AIO contexts, one for each transfer
direction.
=> Fix IIOD's USB interface

iiod/serial.c
Fix the following sparc build failure raised since version 0.24 and https://github.com/analogdevicesinc/libiio/commit/2d3cae005f364742b3a9e7234d15b2fd2cbac664:
```
/home/buildroot/autobuild/instance-0/output-1/build/libiio-0.24/iiod/serial.c: In function 'serial_configure': /home/buildroot/autobuild/instance-0/output-1/build/libiio-0.24/iiod/serial.c:99:58: error: 'B2500000' undeclared (first use in this function); did you mean 'B1500000'?
99 | #define CASE_BPS(bps, attr) case bps: (attr)->c_cflag |= B##bps; break
|                                                          ^
/home/buildroot/autobuild/instance-0/output-1/build/libiio-0.24/iiod/serial.c:127:9: note: in expansion of macro 'CASE_BPS'
127 |         CASE_BPS(2500000, &tty_attrs);
|         ^~~~~~~~ …
```
=> iiod/serial.c: fix sparc build

examples/ad9361-iiostream.c
PlutoSDR devices don't support changing the rf_port_select attribute,
because its fixed in the device tree. Therefore this error should not lead
to a shutdown for these type of devices.
Fixes: https://github.com/analogdevicesinc/libiio/issues/894
Signed-off-by: Benjamin Menküc <benjamin@menkuec.de>
=> ad9361-iiostream: Fix rf_port_select for PlutoSDR devices

CMakeLists.txt
Without the NO_SYSTEM_ENVIRONMENT_PATH option, find_package() would result on my system in a random toolchain's libxml2 library/include paths to be picked, just because it happens to be in $PATH (with a low priority).
=> CMake: Fix detection of libxml2

network-unix.c
Update wait_cancellable() to return -EPIPE if the remote closed the connection or the network link was lost, only when writing; otherwise, a follow-up send() would get a SIGPIPE.
When reading, recv() will return zero as soon as all bytes have been read from the input stream, and won't trigger a SIGPIPE.
=> network: Avoid SIGPIPE on send()

iiod-client.c
Tinyiiod may not handle the TIMEOUT command. This shouldn't prevent us from creating a IIO context, so in the case where we get a -22 error (aka. command does not exist), continue the context creation as usual.
=> iiod-client: Restore support for tinyiiod based programs

usb.c
In usb_shutdown(), destroy the USB I/O context structure after destroying the IIOD client, to address a use-after-free issue.
=> usb: Destroy USB I/O context after IIOD client

channel.c
Support attribute names that start with the channel's label to avoid breaking compatibility with old kernels, which did not offer a 'label' attribute, and caused Libiio to sometimes misdetect the channel's extended name as being part of the attribute name.
Copy of #394 but rebased for the master branch.
=> channel: Support attribute names that start with the channel's label

tests/iio_stresstest.c
On error, calloc() returns NULL. Or a successful call to calloc() with nmemb or size equal to zero.
In the past, we would not catch that, and just start operating on the null pointer (crashing). So catch that, and gracefully error out.
=> utils: catch calloc memory failures in iio_stresstest

network.c, usb.c, xml.c
A few times we are using strtol and strtoul, where we were not setting errno to zero, and then checking it afterwards - this could lead to undefined behaviour based on end user inputs, so do like the man page suggests.
=> set errno to 0, and check after calling library functions

azure-pipelines.yml
Add `sudo apt-get update` command for ARM builds to eliminate "Fail to fetch" error.
=> CI:fix ARM error

CMakeLists.txt
we currently don't tell people if we are or aren't installing udev rules (which I think is an oversight). So do that.
=> cmake: tell people if we are/are not install udev rules

channel.c
In the case where we want to read all attributes of a channel, we need to call iio_channel_attr_read() with the 'attr' argument set to NULL. So we skip searching for an attribute in this case.
This was found when calling iio_channel_attr_read_all() which was causing a segmentation fault:
0: __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:116
1: iio_channel_do_find_attr  (chn=0x555555ddf950, name=0x0)
2: iio_channel_find_attr (chn=0x555555ddf950, name=0x0)
3: iio_channel_attr_read ()
4: iio_channel_attr_read_all ()
=> channel: Don't lookup attributes in special case of reading all attrs

azure-pipelines.yml
CentOS 7 has very old kernel headers which don't support libusb. This updates our builds to disable that feature for them
=> Add CentOS 7 fix to disable USB requirement

CMakeLists.txt, cmake/cmake_uninstall.cmake.in
Per the request #694, this adds an "uninstall" target, which is (a) good form, and (b) requested by Jeff Long, and will make PyBOMBs work more natively.
=> add uninstall target

examples/iio_adi_xflow_check.c, man/iio_common_cmds.1, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c
Today, when debugging things - its sometimes tricky to tell which version of things are installed, since downstream distirbutions split iio-utils and libiio. This commit adds an new option "-V" or "--version" to things to print out the utility version, and the library version (which hopefully matches) seperately.
=> utils: add 'version' option to each util

iiod/iiod.c, iiod/ops.h, iiod/thread-pool.c, iiod/thread-pool.h, iiod/usbd.c
Handle USR1 as a signal that IIOD should re-create the IIO context.
This allows support for hot-plugging IIO devices at runtime; the USR1
signal can then be sent from a udev script, for instance.
=> iiod: Re-create IIO context when receiving USR1 signal

local.c
No functional change.
Per: https://www.ietf.org/archive/id/draft-knodel-terminology-09.html remove some exclusionary language that was in the codebase.
=> local: change exclusionary language

cmake/LinuxPackaging.cmake
Update the generated .deb's metadata to enforce that it cannot be installed alongside the version of libiio shipped in the Debian repositories.
Fixes #923.
=> cmake: Handle conflict between generated .deb and Debian package

cmake/LinuxPackaging.cmake
CMake doesn't really like multi-line strings and considers it as a semicolon-separated list.
=> cmake: Fix invalid Provides: field in Debian packages

README_BUILD.md
Github was getting confused as it thought some rows had two cells and others had three.
=> README_BUILD.md: Fix Github not displaying array properly

.codespell-ignore.txt
Otherwise Codespell fails when processing the examples.
=> codespell: ignore 'MiS'

iiod/ops.c
Pass the error code to the connected clients, instead of disconnecting them.
This means that for a very slow device, a connected client will simply get a -ETIMEDOUT error when a configured timeout expires, and will still be able to communicate with the server.
Fixes: #981.
=> IIOD: Better handle errors of iio_buffer_{refill,push}

CMakeLists.txt
Prior to this, only the library was discovered using pkg-config, while the header was searched manually. This caused troubles on the CI when building for OSX, as it would succeed to find the library but not the header file.
Now, the manual search is now performed only when pkg-config cannot locate a libusb package; which is what was already done for the library file itself.
=> CMake: Find libusb include dir using pkg-config

dns_sd_windows.c
It should use "%zu" to print a size_t.
This fixes a compiler warning under MinGW when the log level is set to Debug.
=> dns_sd_windows: Fix invalid printf format string

CI/azure/macos_tar_fixup.sh
Create a symbolic link for libusb-1.0.0.dylib because iio tools is linked to libusb-1.0.0.dylib but we have libusb-1.0.dylib on machines.
=> CI: fix macOS tar balls

device.c
If we consider a system where channel 0 delivers 32-bit data and channel 1 delivers 16-bit data, the sample size computed would be (4 + 2) == 6 bytes.
This is not correct, as it does not take into account the padding needed until the next sample, which must be computed in a way that all the elements of the next sample are aligned to their own size.
This new algorithm follows what the Linux kernel does (see: iio_compute_scan_bytes() in drivers/iio/industrialio-buffer.c as of v6.4).
This should fix a practical issue with the ADIS16475 driver, reported by @rbolboac.
=> device: Fix sample size calculation

dns_sd.c, local.c
This fixes two minor things in the scan context.
- an off by one error (we never printed out all the device names)
- an extra space in the device names in local contexts, so it matches usb and network scan contexts.
-Robin
=> fix device names in scan

CI/azure/macos_tar_fixup.sh
- Install the dependencies to Library/Frameworks/iio.framework/Versions/Current/Dependencies, and fix the rpath which did not work properly.
- Fix the broken symbolic links in /usr/local/{lib,include}
=> CI: OSX: Fix rpath of libiio + dependencies

CMakeLists.txt, bindings/cpp/CMakeLists.txt, bindings/csharp/CMakeLists.txt, bindings/python/CMakeLists.txt, examples/CMakeLists.txt, iiod/CMakeLists.txt, tests/CMakeLists.txt
CMake v3.10 is from 2018. All stable distributions like Ubuntu 18.04, OpenSUSE 15 or CentOS 7 provide a version of CMake >= 3.10.
Since CMake v3.27 refuses to build anything that claims compatibility with CMake 2.x, bump the minimal required version to CMake 3.10.
=> CMake: Bump minimal required version to 3.10

serial.c
Instead of overriding the context description that comes from the XML, pass the serial port name and description as context attributes, and keep the context description as-is.
Fixes #926.
=> serial: Pass port name/description as context attributes

dns_sd.h, dns_sd_avahi.c, dns_sd_bonjour.c, dns_sd_windows.c
The previous code was very complex as it was handling A and AAAA records as well as SRV records, supposedly to support very old versions of Avahi which sent incomplete or broken SRV records.
Since the version of Avahi we currently use seems to send us SRV records containing all the information we need, we can't reproduce the original issue - and therefore the code can be simplified greatly.
=> dnssd: windows: Greatly simplify code

CMakeLists.txt, debug.h
Remove the coloring feature, because the WITH_COLOR_DEBUG macro was not set anywhere, and would trigger compilation errors when set (since we enforce strict C99 compliance).
The log macros are also not conditionally-compiled anymore, and rely on the compiler detecting them as dead code instead. This should fix all issues with variables detected as unused by the compiler when the 'NoLog' level is used.
=> debug.h: Update log macros

examples/iio_adi_xflow_check.c, tests/iio_attr.c, tests/iio_common.c, tests/iio_common.h, tests/iio_genxml.c, tests/iio_info.c, tests/iio_readdev.c, tests/iio_reg.c, tests/iio_writedev.c
The tools (as well as the iio_adi_xflow_check program) will now return 1 when scanning failed, or 0 when scanning detected at least one IIO context.
=> tests: Standardize programs error codes when scanning

CI/azure/macos_tar_fixup.sh
The dependencies are under /opt/homebrew in the build machine that builds for OSX arm64, and under /usr/local in the other build machines.
=> CI: Fix OSX 11 & 12 tarballs not containing dependencies

local-mmap.c
The algorithm for allocating new blocks was broken, as it was requesting an allocation of (nb_blocks + 1) blocks instead of a single block.
Fixes #1042.
=> local-mmap: Fix block allocation

.github/workflows/freebsd.yml
PR adds FreeBSD as a CI job. Right now USB and avahi are disabled since the build fails. Looks like Avahi is broken in ports for 12.x at least
Please comment if this should include other BSD versions or flavors or something else
=> Add FreeBSD CI build

compat.c, device.c, include/iio/iio.h
This function can be implemented with other libiio functions. The
callers that need it should implement it themselves.
=> Remove API function iio_device_identify_filename()

CI/publish_deps.ps1
The Azure Pipelines 'windows-2022' image uses the latest version of GHC (9.6.2).
=> CI/publish_deps.ps1: Fixing ghcup version

channel.c
iio_channel_attr_write_all calls iio_channel_attr_write with attr set to NULL, causing a segmentation fault
when attr is NULL, the iio_channel_find_attr step in iio_channel_attr_write is skipped
=> channel: don't look for attributes for iio_channel_attr_write_all

local.c
This partially reverts 3fa8e97b. This commit is from 2014, I have no idea why we wanted -EIO for empty attributes. Maybe I thought that this would never happen.
Fixes #1061.
=> local: Fix reading of empty attributes

compat.c, device.c, iiod-client.c, iiod/ops.c, iiod/responder.c, include/iio/iio-backend.h, include/iio/iio.h, include/iio/iiod-client.h, local.c, network.c, serial.c, usb.c, utils/iio_info.c
Change the prototype from:
```c
int iio_device_get_trigger(const struct iio_device *dev, const struct iio_device **trigger);
```
to:
```c
const struct iio_device * iio_device_get_trigger(const struct iio_device *dev);
```
And return errors as pointer-encoded codes.
=> Update iio_device_get _trigger

block.c, iiod-client.c, iiod/responder.c, include/iio/iio.h, local-mmap.c, stream.c
This is a subset of #1035, which does not depend on the DMABUF IIO interface being merged into the upstream Linux kernel.
I create a separate PR so that these can be merged sooner.
=> Enhance blocks API

azure-pipelines.yml
Install 9.2.8 version of ghc because it's not supported anymore on windows-2022 image from azure.
=> Fix MinGW build

.github/workflows/freebsd.yml
A FreeBSD 12.3 CI build takes less than 10 minutes. However, FreeBSD 13.2 will currently hang somewhere, causing the CI to fail after a timeout of 6 hours.
Since that's way too long, reduce the maximum CI time for FreeBSD to 30 minutes.
=> CI: Limit FreeBSD CI time to 30 minutes

azure-pipelines.yml
Switch to new agent on mini mac arm64.
=> CI:switch to new macOS arm64 agent

iiod/dns-sd.c
In the past, we were only checking hostname, as a way to see if the network was ready, but unfortantely - that doesn't work. The kernel really only needs to have a hostname set for uname() to work, which is what glibc and uclibc actaully do in gethostname().
So - now we actualyl check there is a working, configured ethernet card, that supports mdns (ie multicast) that is up before moving on to making sure there is a hostname.
We also don't allow "none" or "(none)" to be the hostname until after things time out (3 min).
This fixes #1072 and turns:
192.168.2.1:5353 : answer _iio._tcp.local. PTR "iiod on (none)._iio._tcp.local." rclass 0x1 ttl 10 length 17 into:
192.168.2.1:5353 : answer _iio._tcp.local. PTR "iiod on pluto._iio._tcp.local." rclass 0x1 ttl 10 length 16
=> iiod: Make sure network is alive before poking avahi

CMakeLists.txt, compat.c
After the new attributes API was introduced, the compatibility layer started to fail, but only on non-local backends.
This was caused by local Libiio symbols being incorrectly linked to the compatibility layer. The call to `iio_channel_get_attr` in `iiod_client_read_attr_new` would resolve to the compatibility layer's `iio_channel_get_attr`, which returns a string instead of a `struct iio_attr *`, and caused all kinds of weird problems further down.
This happened because by default the linker will search for any symbol in the global symbol table, instead of searching in priority in the shared library that contains the code. Since the v0.25 "iio_info" (used in this test) would call `iio_channel_get_attr` before calling `iio_channel_attr_read`, the compat layer's `iio_channel_get_attr` …
=> Fix compatibility layer

bindings/python/iio.py, include/iio/iio.h
Small PR with fixes that didn't really fit anywhere else.
=> Miscellaneous fixes

channel.c
It was using iio_channel_convert_inverse() instead of iio_channel_convert() to convert the raw samples into readable samples.
=> channel: Fix iio_channel_read()

compat.c, iiod-responder.c, serial.c, task.c
- Make sure the serial backend will properly exit and not lock up when iio_context_destroy is called;
- Handle clients sending the BINARY command in ASCII when IIOD is already in binary mode (which happens when a new client connects)
- Fix iio_context_clone() in the compat layer, which should return -ENOSYS with the serial backend, as only one context can be created at the same time. This fixes iio-osc running on top of the compat layer when using the serial backend.
=> Serial backend fixes

README_BUILD.md, iio-config.h.cmakein, iiod/CMakeLists.txt, iiod/interpreter.c, iiod/ops.c, iiod/ops.h
Add support for compiling only with the binary interface, stripping away the ASCII protocol implemented in ops.c, and the flex/bison interpreter.
=> iiod: support compiling without v0.x compatibility

CMakeLists.txt, iiod-responder.c, iiod-responder.h, iiod/dns-sd.c, iiod/parser.y, utils/iio_common.c, utils/iio_common.h, utils/iio_event.c, utils/iio_genxml.c, utils/iio_info.c
Build everything (Libiio, IIOD, and iio-utils) with -Werror or the Visual Studio equivalent, and fix a bunch of warnings that were reported.
=> Build everything with -Werror

xml.c
libxml 2.12.0 reorganized includes, resulting in the following no longer being in scope:
- XML_PARSE_DTDVALID
- xmlReadMemory
- xmlReadFile
- xmlCleanupParser
=> xml: Fix compatibility with libxml 2.12

xml.c
libxml 2.12.0 reorganized includes, resulting in the following no longer being in scope:
- XML_PARSE_DTDVALID
- xmlReadMemory
- xmlReadFile
- xmlCleanupParser
Signed-off-by: Jan Tojnar <jtojnar@gmail.com>
(cherry picked from commit bb688d04294dda45e68dfaf13e3bc1187841e52a)
=> [v0] xml: Fix compatibility with libxml 2.12

block.c, buffer.c, iio-private.h, iiod-client.c, iiod/ops.c, include/iio/iio-backend.h, include/iio/iiod-client.h, local.c, network.c, serial.c, usb.c, utils/iio_common.c
Some misc. fixes, alongside a rework of the interface to v0.x IIOD, which did not support cyclic buffers properly.
Fixes #1097.
=> Fix cyclic mode to IIOD v0.x

examples/ad9361-iiostream.c, examples/ad9371-iiostream.c, examples/adrv9002-iiostream.c, examples/adrv9009-iiostream.c
This fixes a few typos introduced with the update to the new API
Fixes: 99688f2dcc19 ("examples: Update to the new API")
=> examples/*-iiostream: Fix [rx|tx]_sample_sz initialization

bindings/python/iio.py
Trigger() is being passed device contents, but no context, and therefore fails like so:
|>>> adc._ctrl.trigger
|Traceback (most recent call last):
|  File "<stdin>", line 1, in <module>
|  File "/home/baylibre/git/pyadi-iio/venv/lib/python3.10/site-packages/iio.py", line 1281, in _get_trigger
|    trig = Trigger(value.contents)
|TypeError: Trigger.__init__() missing 1 required positional argument: '_device'
Pass self.ctx as the first argument so that the trigger is properly instantiated.
Fixes #1107.
=> iio.py: fix Trigger instantiation

iiod/network.c
Otherwise, the AIO code will throw -AGAIN errors.
=> iiod: Open non-blocking sockets only when not using AIO

local.c, local.h
The problem of leaving it opened at all times is that other instances of Libiio cannot be ran in parallel.
Fixes #1111.
=> local: Avoid keeping buffer FD opened at all times

buffer.c, context.c, iiod-responder.c, local.c, network.c, utils/iio_rwdev.c
Fix some out-of-scope references, memory leaks, use-after-free, among other things.
=> Misc. fixes

channel.c, include/iio/iio.h
Add the IIO_MOD_LIGHT_UVA and IIO_MOD_LIGHT_UVB modifiers that will be introduced in Linux v6.8.
Note that Linux v6.8-rc1 added those entries in the middle of the iio_modifier enum (which is wrong as it breaks ABI), but it will be fixed for the regular v6.8 release.
Fixes #1130.
=> iio.h: Add IIO_MOD_LIGHT_UVA/UVB modifiers

bindings/cpp/iiopp.h, bindings/python/iio.py, compat.c, context.c, iio-private.h, iiod/iiod.c, include/iio/iio.h, utils/iio_genxml.c
Instead of returning a string allocated alongside the IIO context, it
will now return a string allocated on the heap, that has to be freed
with free() afterwards. The function can now also return errors.
The advantage of this change is multiple:
- IIO contexts now don't have a huge XML string allocated during their
whole lifetime;
- If the application does not call iio_context_get_xml(), then all the
internal functions used to generate the XML string in the first place
are dead code, and when building statically, can be garbage-collected.
C# bindings will be updated by @AlexandraTrifan  in #1122.
=> Rework iio_context_get_xml()

iiod-client.c, iiod-responder.c, iiod/ops.h, iiod/responder.c, include/iio/iiod-client.h, network.c, serial.c, usb.c
Rework how the blocks and buffers are identified and destroyed when using the USB backend; previously, nothing would be freed.
=> USB context fixes

iiod/init/iiod.service.cmakein
Systemd now gives a warning when IIOD_EXTRA_OPTS is unset.
This change sets it to an empty string by default while still allowing it be overridden by /etc/default/iiod.
Fixes #1142.
=> iiod: Add default env var to service file

azure-pipelines.yml
There are two different python versions installed inside the Microsoft Azure macos containers.
Install setuptools for the default python.
Specify which python cmake should use (the one for which the setuptools package was installed).
=> azure_pipelines.yml: Fix macos CIs

attr.c, attr.h, context.c, device.c, iio-private.h, include/iio/iio-backend.h, local.c, serial.c, xml.c
Modify/add functions:
- `iio_context_add_device`, which will create a `iio_device` and add it to the context;
- `iio_device_add_channel`, which will create a `iio_channel` and add it to the device;
- The functions `iio_{context,device,channel}_add_attr` to add attributes to contexts/devices/channels are now backend API
- `iio_create_context_from_backend` now takes a few extra parameters that will be used to create the iio_context.
With these changes, the XML backend was updated to be fully implemented on top of the public API (be it iio.h or iio-backend.h) and does not use iio-private.h anymore.
In theory, the local backend could do that too but it's a lot more work (due to how it currently creates the context).
The code should be considered very experimental, it was not thoroughly …
=> Better backend API

bindings/python/iio.py
When reading an attribute a buffer of size 1024 bytes is used by the python bindings of libiio (iio.py:762). This is not enough space for large attributes, such as `gain_table_config` of an AD9361 ('ad9361-phy'), which is 1688 bytes. This PR increases the buffer size to 4096 bytes.
This is a bit of a brute-force solution. Ideally, iiod would be able to inform the caller of the required buffer space, or the caller could use an incrementally growing buffer. I think the simple solution of using a larger buffer is ok though.
=> Increase attribute read buffer space

serial.c
On Linux and MacOS the serial connection handler has the DTR flag configured as ON by default. 
The Windows handler has it OFF by default, which prevents a successful serial connection because the driver expects it to be ON.
This issue can be reproduced using UART over USB. The first serial connection through libiio will block while initializing due to this flag. Using a different terminal emulator for the first connection will set the DTR flag to ON. Any subsequent libiio connection (prior to a reset) will be functional.
Serial connection opening is handled separately for Windows (can be checked in libserialport: https://github.com/sigrokproject/libserialport/blob/master/serialport.c#L488 and  https://github.com/sigrokproject/libserialport/blob/master/serialport.c#L549 ).
=> serial.c: force DTR serial connection flag to ON for Windows clients

CI/publish_deps.ps1, serial.c
Cherry-pick commits from libiio-v0 to 2022_r2 in order for CIs to pass.
=> Cherry pick to 2022 r2

CODE_OF_CONDUCT.md, mainpage.dox, man/iio_rwdev.1.in
Remove spelling issues that cause the CodeSpell check to fail everytime.
=> Fix spelling issues

CI/publish_deps.ps1, libiio.iss.cmakein
Add libzstd.dll to windows installer and windows packaged zips. 
Fixes issue https://github.com/analogdevicesinc/libiio/issues/1153
=> Include libzstd.dll in windows artifacts

CI/azure/prepare_assets.sh
We dropped support for macOS 11, but it was not removed from the script that prepares the artifacts for the release. This causes the script to fail.
=> CI/azure/prepare_assets: remove macOS 11

README_BUILD.md, block.c, iio-config.h.cmakein, iiod/CMakeLists.txt, iiod/ops.h, iiod/responder.c, iiod/usb-dmabuf.c, include/iio/iio-backend.h, include/iio/iio.h, local-dmabuf.c, local.c, local.h
Follow-up of https://github.com/analogdevicesinc/libiio/pull/928
These commits will modify how the local-DMABUF interface works, because the interface itself in the kernel changed (as it is not yet upstream).
The local backend will now make use of the "udmabuf" kernel driver, which was added in 5.19, to create DMABUF objects from memfd buffers. These DMABUFs can then be attached to the IIO device and/or other devices from other subsystems, and memory-mapped to access the data.
IIOD has also been modified to support enqueueing DMABUFs to the USB (functionfs) interface, and will support passing the buffers between IIO and USB in a zero-copy fashion.
From a Libiio API standpoint, some changes were introduced:
- `iio_block_enqueue` will support partial transfers on RX buffers as well;
- …
=> DMABUF API v3

iiod/CMakeLists.txt, iiod/init/iiod.service.cmakein
Make sure iiod service looks in the path for hwmon devices too , fixes issue https://github.com/analogdevicesinc/libiio/issues/1194
=> iiod: ensure service starts with only hwmon devs

iiod/responder.c
responder.c will switch to MIT, while thread-pool.h apparently stays LGPL; drop the unnecesary header include to avoid problems.
- Please replace this comment with a summary of your changes, and add any context
necessary to understand them. List any dependencies required for this change.
- To check the checkboxes below, insert a 'x' between square brackets (without
any space), or simply check them after publishing the PR.
- If you changes include a breaking change, please specify dependent PRs in the
description and try to push all related PRs simultaneously.
- [x ] Bug fix (a change that fixes an issue)
=> iiod: Drop unnecesary include

iiod/init/iiod.service.cmakein
Removing extraneous $ in the assignment of IIOD_EXTRA_OPTS in the service file that was part of https://github.com/analogdevicesinc/libiio/commit/a436ad602835dddaa297a7040abbd8f24a879af5
Fixes #1142.
=> Fixed invalid IIOD_EXTRA_OPTS assignment

iiod/init/iiod.service.cmakein
Fixing an invalid assignment of IIOD_EXTRA_OPTS in the service file. Causing the warning "Referenced but unset environment variable evaluates to an empty string: IIOD_EXTRA_OPTS" if not set in /etc/default/iiod.
Fixes #1142.
=> Fixes invalid IIOD_EXTRA_OPTS assignment

azure-pipelines.yml
Remove CI jobs for macos-12 since the image has been deprecated by Azure DevOps.
Deprecation announcement at:
https://devblogs.microsoft.com/devops/upcoming-deprecation-of-macos-12-hosted-pipeline-image
"Azure DevOps is starting the deprecation process for the macOS-12.."
"..the image will be fully unsupported by January 8, 2025"
=> CI: Remove support for macos-12 as it's no longer hosted on azure

cmake/cmake_uninstall.cmake.in
exec_program() has been deprecared. This PR updates a cmake file to use execute_process() instead.
=> cmake: Replace deprecated exec_program() with execute_process()

examples/ad9361-iiostream.c, examples/ad9371-iiostream.c, examples/adrv9002-iiostream.c, examples/adrv9009-iiostream.c, examples/dummy-iiostream.c, examples/iio-monitor.c, utils/gen_code.c, utils/iio_genxml.c, utils/iio_stresstest.c
Replace old way of checking pointers returned by iio_create_context().
The pointers returned by iio_create_context() need to be checked with iio_err().
=> Check the encoded error in the iio structures for utils and examples

mainpage.dox
Error message: "Error: ./mainpage.dox:231: re-used ==> reused"
Fix minor spelling error found by CI.
=> dox: Fix minor spell error reported by CI

include/iio/iio.h
The C11 generic macros iio_attr_{read,write} cannot be accesed from a program built with C++. Adding the __cplusplus guard for these functions will ensure that C++ users do not accidentally use these (resulting in an error). The reason for these changes were also discussed here: #1240 
- Add ifndef __cplusplus to iio_attr_{read,write}  functions.
=> iio.h: Remove c++ access to c only functions

bindings/cpp/iiopp.h
Missed `inline` keyword before a couple of functions in `bindings/cpp/iiopp.h` . Since I included it in two .cpp files and no more "multiple definitions", that should be all missed inlines.
=> [FIX] missed `inline`s in C++ binding

lock-windows.c
Send the same parameters as the Unix implementation: https://github.com/analogdevicesinc/libiio/blob/e54973a39f6f35fda3cf170d8585d48d65450e7b/lock.c#L131
This was causing random crashes when running iio_info on Windows. Error was: "0xC0000005: Access violation executing location".
- Please replace this comment with a summary of your changes, and add any context
necessary to understand them. List any dependencies required for this change.
- To check the checkboxes below, insert a 'x' between square brackets (without
any space), or simply check them after publishing the PR.
- If you changes include a breaking change, please specify dependent PRs in the
description and try to push all related PRs simultaneously.
=> lock: Fix passing the wrong parameter when creating threads on Windows

lock.c
If HAS_PTHREAD_SETNAME_NP is not set, then PTHREAD_MAX_NAMELEN_NP will not be set and therefore the compilation fails. Instead of adding more '#idefs' let's just take PTHREAD_MAX_NAMELEN_NP of the HAS_PTHREAD_SETNAME_NP block.
On top of this, if HAS_PTHREAD_SETNAME_NP is not set, then iio_thrd_create_set_name() is defined to 0 which has no effect since we don't do any error handling when calling iio_thrd_create_set_name(). This was a leftover from the first versions of the patch series.
(this was found on a petalinux build where the toolchain does not include pthread_setname_np())
=> lock: fix build when HAS_PTHREAD_SETNAME_NP is not set

iiod/interpreter.c
'readfd_io' and 'writefd_io' are used when building with cmake flag WITH_AIO=OFF. They are used here: https://github.com/analogdevicesinc/libiio/blob/73bba2572c0710190b46e00242ca1e99095838e8/iiod/interpreter.c#L165-L166
This reverts commit a80a31274e0c01b64dabb81c3bb4e41c09355ce8.
- Please replace this comment with a summary of your changes, and add any context
necessary to understand them. List any dependencies required for this change.
- To check the checkboxes below, insert a 'x' between square brackets (without
any space), or simply check them after publishing the PR.
- If you changes include a breaking change, please specify dependent PRs in the
description and try to push all related PRs simultaneously.
=> Revert removing iiod interpreter calls

stream.c, utils/iio_rwdev.c
This improves iio_rwdev exit and is a combination of two things:
1. When destroying the stream, make sure to dequeue any possible in flight block before destroying it. This makes for a much cleaner exit specially in cases where freeing the blocks is deferred to the default client which for some reason will make iiod choke for sometime on a io_submit() call related to in flight block dequeue;
2. With 1), we don't really want to cancel the buffer as soon as we hit ctrl-c since then we would timeout in dequeing the block. And if we don't do 1), then we would still have the delay caused by iiod (since with #1243, iiod now makes sure it's safe to free a block before freeing it).
So this is really a combination of the above two points which improves things a lot when cancelling a buffer session …
=> Misc improvements

device.c
The XML already contains channels in a sorted order.
These changes reduce context creation time, but the primary reason for implementing them is to address differences in channel sorting behavior between Windows and Linux. These differences cause communication issues between libiio running on Windows and the remote IIOD.
More specifically, when all channels lack an index (marked with a value of -2), qsort() on Linux preserves the original order since there is nothing to sort. However, on Windows, the channel list is modified each time qsort() is called.
The channel's position in the list is critical because it is used by the binary interface with IIOD.
The first symptom of this issue was the failure to create an iio_context. Internally, this process reads all scale attributes from all …
=> device.c: Avoid reordering channels for XML based iio contexts

CMakeLists.txt, examples/CMakeLists.txt, examples/adrv9002-iiostream.c, iiod/CMakeLists.txt, iiod/ops.c, iiod/responder.c, tinyiiod/CMakeLists.txt, utils/CMakeLists.txt, utils/iio_common.c
Based on discussion at https://github.com/analogdevicesinc/libiio/issues/1223 do the following:
- apply a set of compiler flags not just to libiio but also to utils, examples and iiod.
- make sure the set of flags will not be enforced to libiio clients
- fix warnings generated after the set of flags has been applied
=> Forward libiio compiler flags to in house clients

iiod/responder.c
On handle_free_block(), we need to make sure to unlock the buffer_entry lock if we fail to get the IIO block.
=> iiod: responder: make sure to unlock buffer_entry lock

bindings/cpp/iiopp.h, bindings/csharp/IOBuffer.cs, bindings/python/iio.py, buffer.c, compat.c, iio-private.h, iiod-client.c, iiod/responder.c, include/iio/iio-backend.h, include/iio/iio.h, include/iio/iiod-client.h, local-dmabuf.c, local.c, local.h, network.c, serial.c, usb.c, utils/iio_rwdev.c, utils/iio_stresstest.c
See #1260
Therefor this PR impelments the possibility to decide which block is using CMA at runtime using a newly introduce `struct iio_block_params` struct.
Reviewing of the general idea requested.
=> task: Implement iio_buffer_params struct and make CMA selectable at runtime

bindings/python/doc/device.rst, bindings/python/iio.py
When checking if the return type of a function is null, it makes sense to raise an exception when something malfunctioned. If everything worked well but the result type is nothing then it shouldn't be treated as a problem. For example, one could:
- search for a device that isn't available on the system
- search for a channel that a device doesn't have
- search for an attribute that isn't available
- etc.
=> python: Raise exception when an actual error occured

CMakeLists.txt
Since iio-bachend.h is a also a public header, make sure it gets installed along with the other public headers.
iio-backend.h is required when defining a custom external backend within a client code.
=> CMake: Install public header iio-backend.h along with the rest

iio.h
Sync libiio iio events with latest kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/iio/types.h?id=34934d79965518548d33c0513a9572ae936d8c29
=> iio.h: Update iio event and direction with latest kernel

bindings/csharp/IIOEvent.cs, bindings/python/iio.py, include/iio/iio.h, utils/iio_event.c
Update C, C#, Python to include the new:
- IIO event type: IIO_EV_TYPE_FAULT
- IIO event direction: IIO_EV_DIR_FAULT_OPENWIRE
=> Sync with latest iio events

azure-pipelines.yml
Remove qemu package and install qemu-user-static
=> Modify qemu

local-dmabuf.c
To create an IIO block associated with a buffer, local_create_block() attempts to use the DMABUF API, and if that fails it uses the MMAP API. However, the availability check for the DMABUF API in local_create_dmabuf() is incomplete: In recent kernels the DMABUF IOCTLs are available, but still, the DMABUF related iio_buffer_access_funcs may not be implemented for the buffer used in the kernel driver [1], [2]. In this case, the returned error is propagated through local_create_block() up to the caller and block setup fails without an attempt to use one of the alternative interfaces.
To fix this issue, add another check for the error code set by the DMABUF attach IOCTL and mark the DMABUF interface as unavailable.
[1]: https://elixir.bootlin.com/linux/v6.14.3/source/drivers/iio/industrialio-b …
=> local-dmabuf: Improve checks for DMABUF interface support

local.c
Currently local_enable_buffer() can not be used to disable IIO buffers. First, instead of propagating the value of the enable parameter to the call to local_do_enable_buffer() a hard-coded value is used. And second, setting both the buffer length and watermark attributes is attempted not only in the enable case but also in the disable case for an already active buffer. This causes local_enable_buffer() to fail early.
To fix the issue, only set buffer attributes in the enable case and properly propagate the requested action to local_do_enable_buffer().
=> local: Fix disabling of IIO buffers in local_enable_buffer

include/iio/iio.h
Only 'params' can be NULL, the 'mask' parameter needs to be a valid pointer.
Fix description for the parameters of iio_device_create_buffer().
=> iio.h: Fix desctiption for iio_device_create_buffer()

CI/azure/check_README_BUILD.sh
This adds a test to ensure that cmake options are printed out via the cmake toggle_iio_feature macro.
=> cmake: ensure cmake options are printed out

CMakeLists.txt, bindings/cpp/CMakeLists.txt, bindings/csharp/CMakeLists.txt, bindings/python/CMakeLists.txt, examples/CMakeLists.txt, iiod/CMakeLists.txt, tinyiiod/CMakeLists.txt, utils/CMakeLists.txt
-Bsymbolic is intended for dynamic linking and so it doesn't make sense to used when building a static library. User modern cmake approach to apply the flag only to the library and not globally to all targets.
=> CMake: Use linker flag -Bsymbolic only on the shared library

CMakeLists.txt, bindings/cpp/CMakeLists.txt, bindings/cpp/examples/iiopp-enum.cpp, bindings/cpp/iio.hpp, mainpage.dox
Rename the cpp header file to better match standard conventions.
- This matches the project name, avoids confusion, and follows the common convention of .h for C headers and .hpp for C++ headers.
- Anyone looking at the two files will immediately understand iio.h is for C, iio.hpp is for C++.
- This leaves the namespace as the existing iiopp, to avoid too much pain for those using things.
=> rename iiopp.h to iio.hpp

include/iio/iio.h
In version 0 the attributes were strings while in version 1 they are represented by an iio_attr. It's likely that the old description wasn't updated.
=> iio.h: Fix description for API that returns an iio_attr struct

usb.c
Warning:
D:\a\1\s\usb.c(152,31): error C2220: the following warning is treated as an error [D:\a\1\s\build-msvc\iio.vcxproj] D:\a\1\s\usb.c(152,31): warning C5287: operands are different enum types 'libusb_request_type' and 'libusb_request_recipient'; use an explicit cast to silence this warning [D:\a\1\s\build-msvc\iio.vcxproj]
D:\a\1\s\usb.c(152,31):
to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
Use cast to silence the warnings as they are treated as errors when build is done on CI.
=> usb: Fix warning generated by newer version of MSVC

bindings/python/setup.py.cmakein
=> python: Remove deprecated license classifier. Use 'license' key instead.

utils/iio_info.c
The following build error was caught only by the MSVC 2019 compiler:
`libiio\utils\iio_info.c(39,4): error C2059: syntax error: '}'`
=> utils: Fix improper end of option list

attr.c
Each time a context attribute is added, its value gets appended to a list of values while its name gets appended to a list of names.  But since the names list gets sorted and the values list doesn't, the two lists can become misaligned.
To fix this, after sorting, find where the newly added attribute was inserted. Because the list gets sorted each time a new attribute is added we know attributes positioned after the newly inserted attributes just get shifted towards the end of the list. So we do the same for the values.
=> attr: Fix context attributes getting out of sync with their values

network.c
This pr would close #1333 . 
This issue was initially found on libiio v0.26 but it persists to this version.
Adding this flag to the network would convert SIGPIPIE to EPIPE preventing app crashes on client side.
=> network: add flag to convert SIGPIPE to EPIPE

dns_sd_windows.c
Fix a critical access violation that occurred when `iio_mutex_lock(dd->lock)`
was called in the `query_callback` function. The crash was caused by a data
type mismatch in the callback mechanism:
- The query_callback function expected `user_data` to be a `dns_sd_cb_data*`
- However, `mdns_query_recv` was passing a `dns_sd_discovery_data*` directly
- This caused invalid memory access when trying to dereference `cb_data->d`
=> Fix iio_info crashing when scanning for contexts on Windows
